-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_config6_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    layer5_out_dout : IN STD_LOGIC_VECTOR (511 downto 0);
    layer5_out_empty_n : IN STD_LOGIC;
    layer5_out_read : OUT STD_LOGIC;
    layer5_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer5_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    layer6_out_din : OUT STD_LOGIC_VECTOR (511 downto 0);
    layer6_out_full_n : IN STD_LOGIC;
    layer6_out_write : OUT STD_LOGIC;
    layer6_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer6_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of myproject_dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_config6_s is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_6F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101111";
    constant ap_const_lv32_70 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_8F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001111";
    constant ap_const_lv32_90 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010000";
    constant ap_const_lv32_9F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011111";
    constant ap_const_lv32_A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100000";
    constant ap_const_lv32_AF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101111";
    constant ap_const_lv32_B0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110000";
    constant ap_const_lv32_BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111111";
    constant ap_const_lv32_C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000000";
    constant ap_const_lv32_CF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001111";
    constant ap_const_lv32_D0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010000";
    constant ap_const_lv32_DF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011111";
    constant ap_const_lv32_E0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100000";
    constant ap_const_lv32_EF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101111";
    constant ap_const_lv32_F0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110000";
    constant ap_const_lv32_FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111111";
    constant ap_const_lv32_100 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000000";
    constant ap_const_lv32_10F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100001111";
    constant ap_const_lv32_110 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100010000";
    constant ap_const_lv32_11F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100011111";
    constant ap_const_lv32_120 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100100000";
    constant ap_const_lv32_12F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100101111";
    constant ap_const_lv32_130 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100110000";
    constant ap_const_lv32_13F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100111111";
    constant ap_const_lv32_140 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101000000";
    constant ap_const_lv32_14F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101001111";
    constant ap_const_lv32_150 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101010000";
    constant ap_const_lv32_15F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101011111";
    constant ap_const_lv32_160 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101100000";
    constant ap_const_lv32_16F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101101111";
    constant ap_const_lv32_170 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101110000";
    constant ap_const_lv32_17F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101111111";
    constant ap_const_lv32_180 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110000000";
    constant ap_const_lv32_18F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110001111";
    constant ap_const_lv32_190 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110010000";
    constant ap_const_lv32_19F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110011111";
    constant ap_const_lv32_1A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110100000";
    constant ap_const_lv32_1AF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110101111";
    constant ap_const_lv32_1B0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110110000";
    constant ap_const_lv32_1BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110111111";
    constant ap_const_lv32_1C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111000000";
    constant ap_const_lv32_1CF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111001111";
    constant ap_const_lv32_1D0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111010000";
    constant ap_const_lv32_1DF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111011111";
    constant ap_const_lv32_1E0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111100000";
    constant ap_const_lv32_1EF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111101111";
    constant ap_const_lv32_1F0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111110000";
    constant ap_const_lv32_1FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111111111";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal layer5_out_blk_n : STD_LOGIC;
    signal layer6_out_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal data_fu_197_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_reg_676 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal data_123_reg_681 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_93_reg_686 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_94_reg_691 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_95_reg_696 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_96_reg_701 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_97_reg_706 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_98_reg_711 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_99_reg_716 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_100_reg_721 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_101_reg_726 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_102_reg_731 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_103_reg_736 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_104_reg_741 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_105_reg_746 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_106_reg_751 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_107_reg_756 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_108_reg_761 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_109_reg_766 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_110_reg_771 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_111_reg_776 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_112_reg_781 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_113_reg_786 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_114_reg_791 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_115_reg_796 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_116_reg_801 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_117_reg_806 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_118_reg_811 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_119_reg_816 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_120_reg_821 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_121_reg_826 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_122_reg_831 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_reg_836 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal res_1_reg_841 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_2_reg_846 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_3_reg_851 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_4_reg_856 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_5_reg_861 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_6_reg_866 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_7_reg_871 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_8_reg_876 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_9_reg_881 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_32_reg_886 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_33_reg_891 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_34_reg_896 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_35_reg_901 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_36_reg_906 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_37_reg_911 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_38_reg_916 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_39_reg_921 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_40_reg_926 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_41_reg_931 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_42_reg_936 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_43_reg_941 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_44_reg_946 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_45_reg_951 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_46_reg_956 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_47_reg_961 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_48_reg_966 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_49_reg_971 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_50_reg_976 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_51_reg_981 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_52_reg_986 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_53_reg_991 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_ready : STD_LOGIC;
    signal call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_2 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_3 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_4 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_5 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_6 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_7 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_8 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_9 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_10 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_11 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_12 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_13 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_14 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_15 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_16 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_17 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_18 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_19 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_20 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_21 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_22 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_23 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_24 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_25 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_26 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_27 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_28 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_29 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_30 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_31 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s IS
    port (
        ap_ready : OUT STD_LOGIC;
        data_0_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_1_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_2_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_3_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_4_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_5_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_6_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_7_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_8_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_9_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_10_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_11_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_12_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_13_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_14_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_15_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_16_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_17_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_18_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_19_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_20_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_21_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_22_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_23_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_24_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_25_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_26_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_27_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_28_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_29_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_30_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_31_val : IN STD_LOGIC_VECTOR (15 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_8 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_9 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_10 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_11 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_12 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_13 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_14 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_15 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_16 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_17 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_18 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_19 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_20 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_21 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_22 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_23 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_24 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_25 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_26 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_27 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_28 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_29 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_30 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_31 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_rst : IN STD_LOGIC );
    end component;



begin
    call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161 : component myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s
    port map (
        ap_ready => call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_ready,
        data_0_val => data_reg_676,
        data_1_val => data_123_reg_681,
        data_2_val => data_93_reg_686,
        data_3_val => data_94_reg_691,
        data_4_val => data_95_reg_696,
        data_5_val => data_96_reg_701,
        data_6_val => data_97_reg_706,
        data_7_val => data_98_reg_711,
        data_8_val => data_99_reg_716,
        data_9_val => data_100_reg_721,
        data_10_val => data_101_reg_726,
        data_11_val => data_102_reg_731,
        data_12_val => data_103_reg_736,
        data_13_val => data_104_reg_741,
        data_14_val => data_105_reg_746,
        data_15_val => data_106_reg_751,
        data_16_val => data_107_reg_756,
        data_17_val => data_108_reg_761,
        data_18_val => data_109_reg_766,
        data_19_val => data_110_reg_771,
        data_20_val => data_111_reg_776,
        data_21_val => data_112_reg_781,
        data_22_val => data_113_reg_786,
        data_23_val => data_114_reg_791,
        data_24_val => data_115_reg_796,
        data_25_val => data_116_reg_801,
        data_26_val => data_117_reg_806,
        data_27_val => data_118_reg_811,
        data_28_val => data_119_reg_816,
        data_29_val => data_120_reg_821,
        data_30_val => data_121_reg_826,
        data_31_val => data_122_reg_831,
        ap_return_0 => call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_0,
        ap_return_1 => call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_1,
        ap_return_2 => call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_2,
        ap_return_3 => call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_3,
        ap_return_4 => call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_4,
        ap_return_5 => call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_5,
        ap_return_6 => call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_6,
        ap_return_7 => call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_7,
        ap_return_8 => call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_8,
        ap_return_9 => call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_9,
        ap_return_10 => call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_10,
        ap_return_11 => call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_11,
        ap_return_12 => call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_12,
        ap_return_13 => call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_13,
        ap_return_14 => call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_14,
        ap_return_15 => call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_15,
        ap_return_16 => call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_16,
        ap_return_17 => call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_17,
        ap_return_18 => call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_18,
        ap_return_19 => call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_19,
        ap_return_20 => call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_20,
        ap_return_21 => call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_21,
        ap_return_22 => call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_22,
        ap_return_23 => call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_23,
        ap_return_24 => call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_24,
        ap_return_25 => call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_25,
        ap_return_26 => call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_26,
        ap_return_27 => call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_27,
        ap_return_28 => call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_28,
        ap_return_29 => call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_29,
        ap_return_30 => call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_30,
        ap_return_31 => call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_31,
        ap_rst => ap_rst);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((layer6_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                data_100_reg_721 <= layer5_out_dout(159 downto 144);
                data_101_reg_726 <= layer5_out_dout(175 downto 160);
                data_102_reg_731 <= layer5_out_dout(191 downto 176);
                data_103_reg_736 <= layer5_out_dout(207 downto 192);
                data_104_reg_741 <= layer5_out_dout(223 downto 208);
                data_105_reg_746 <= layer5_out_dout(239 downto 224);
                data_106_reg_751 <= layer5_out_dout(255 downto 240);
                data_107_reg_756 <= layer5_out_dout(271 downto 256);
                data_108_reg_761 <= layer5_out_dout(287 downto 272);
                data_109_reg_766 <= layer5_out_dout(303 downto 288);
                data_110_reg_771 <= layer5_out_dout(319 downto 304);
                data_111_reg_776 <= layer5_out_dout(335 downto 320);
                data_112_reg_781 <= layer5_out_dout(351 downto 336);
                data_113_reg_786 <= layer5_out_dout(367 downto 352);
                data_114_reg_791 <= layer5_out_dout(383 downto 368);
                data_115_reg_796 <= layer5_out_dout(399 downto 384);
                data_116_reg_801 <= layer5_out_dout(415 downto 400);
                data_117_reg_806 <= layer5_out_dout(431 downto 416);
                data_118_reg_811 <= layer5_out_dout(447 downto 432);
                data_119_reg_816 <= layer5_out_dout(463 downto 448);
                data_120_reg_821 <= layer5_out_dout(479 downto 464);
                data_121_reg_826 <= layer5_out_dout(495 downto 480);
                data_122_reg_831 <= layer5_out_dout(511 downto 496);
                data_123_reg_681 <= layer5_out_dout(31 downto 16);
                data_93_reg_686 <= layer5_out_dout(47 downto 32);
                data_94_reg_691 <= layer5_out_dout(63 downto 48);
                data_95_reg_696 <= layer5_out_dout(79 downto 64);
                data_96_reg_701 <= layer5_out_dout(95 downto 80);
                data_97_reg_706 <= layer5_out_dout(111 downto 96);
                data_98_reg_711 <= layer5_out_dout(127 downto 112);
                data_99_reg_716 <= layer5_out_dout(143 downto 128);
                data_reg_676 <= data_fu_197_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                res_1_reg_841 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_1;
                res_2_reg_846 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_2;
                res_32_reg_886 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_10;
                res_33_reg_891 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_11;
                res_34_reg_896 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_12;
                res_35_reg_901 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_13;
                res_36_reg_906 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_14;
                res_37_reg_911 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_15;
                res_38_reg_916 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_16;
                res_39_reg_921 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_17;
                res_3_reg_851 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_3;
                res_40_reg_926 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_18;
                res_41_reg_931 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_19;
                res_42_reg_936 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_20;
                res_43_reg_941 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_21;
                res_44_reg_946 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_22;
                res_45_reg_951 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_23;
                res_46_reg_956 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_24;
                res_47_reg_961 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_25;
                res_48_reg_966 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_26;
                res_49_reg_971 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_27;
                res_4_reg_856 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_4;
                res_50_reg_976 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_28;
                res_51_reg_981 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_29;
                res_52_reg_986 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_30;
                res_53_reg_991 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_31;
                res_5_reg_861 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_5;
                res_6_reg_866 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_6;
                res_7_reg_871 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_7;
                res_8_reg_876 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_8;
                res_9_reg_881 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_9;
                res_reg_836 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, layer6_out_full_n, ap_CS_fsm_state3, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((layer6_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(layer6_out_full_n)
    begin
        if ((layer6_out_full_n = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, layer5_out_empty_n)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (layer5_out_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, layer6_out_full_n, ap_CS_fsm_state3)
    begin
        if (((layer6_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    data_fu_197_p1 <= layer5_out_dout(16 - 1 downto 0);

    internal_ap_ready_assign_proc : process(layer6_out_full_n, ap_CS_fsm_state3)
    begin
        if (((layer6_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    layer5_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, layer5_out_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer5_out_blk_n <= layer5_out_empty_n;
        else 
            layer5_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer5_out_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer5_out_read <= ap_const_logic_1;
        else 
            layer5_out_read <= ap_const_logic_0;
        end if; 
    end process;


    layer6_out_blk_n_assign_proc : process(layer6_out_full_n, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            layer6_out_blk_n <= layer6_out_full_n;
        else 
            layer6_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer6_out_din <= (((((((((((((((((((((((((((((((res_53_reg_991 & res_52_reg_986) & res_51_reg_981) & res_50_reg_976) & res_49_reg_971) & res_48_reg_966) & res_47_reg_961) & res_46_reg_956) & res_45_reg_951) & res_44_reg_946) & res_43_reg_941) & res_42_reg_936) & res_41_reg_931) & res_40_reg_926) & res_39_reg_921) & res_38_reg_916) & res_37_reg_911) & res_36_reg_906) & res_35_reg_901) & res_34_reg_896) & res_33_reg_891) & res_32_reg_886) & res_9_reg_881) & res_8_reg_876) & res_7_reg_871) & res_6_reg_866) & res_5_reg_861) & res_4_reg_856) & res_3_reg_851) & res_2_reg_846) & res_1_reg_841) & res_reg_836);

    layer6_out_write_assign_proc : process(layer6_out_full_n, ap_CS_fsm_state3)
    begin
        if (((layer6_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            layer6_out_write <= ap_const_logic_1;
        else 
            layer6_out_write <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
