// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module myproject_dense_array_ap_fixed_64u_array_ap_fixed_16_6_5_3_0_32u_config4_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer3_out_dout,
        layer3_out_empty_n,
        layer3_out_read,
        layer3_out_num_data_valid,
        layer3_out_fifo_cap,
        layer4_out_din,
        layer4_out_full_n,
        layer4_out_write,
        layer4_out_num_data_valid,
        layer4_out_fifo_cap
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [1023:0] layer3_out_dout;
input   layer3_out_empty_n;
output   layer3_out_read;
input  [1:0] layer3_out_num_data_valid;
input  [1:0] layer3_out_fifo_cap;
output  [511:0] layer4_out_din;
input   layer4_out_full_n;
output   layer4_out_write;
input  [1:0] layer4_out_num_data_valid;
input  [1:0] layer4_out_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer3_out_read;
reg layer4_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer3_out_blk_n;
reg    layer4_out_blk_n;
wire    ap_CS_fsm_state3;
wire   [15:0] data_fu_357_p1;
reg   [15:0] data_reg_1188;
reg    ap_block_state1;
reg   [15:0] data_1_reg_1193;
reg   [15:0] data_2_reg_1198;
reg   [15:0] data_3_reg_1203;
reg   [15:0] data_4_reg_1208;
reg   [15:0] data_5_reg_1213;
reg   [15:0] data_6_reg_1218;
reg   [15:0] data_7_reg_1223;
reg   [15:0] data_8_reg_1228;
reg   [15:0] data_9_reg_1233;
reg   [15:0] data_63_reg_1238;
reg   [15:0] data_10_reg_1243;
reg   [15:0] data_11_reg_1248;
reg   [15:0] data_12_reg_1253;
reg   [15:0] data_13_reg_1258;
reg   [15:0] data_14_reg_1263;
reg   [15:0] data_15_reg_1268;
reg   [15:0] data_16_reg_1273;
reg   [15:0] data_17_reg_1278;
reg   [15:0] data_18_reg_1283;
reg   [15:0] data_19_reg_1288;
reg   [15:0] data_20_reg_1293;
reg   [15:0] data_21_reg_1298;
reg   [15:0] data_22_reg_1303;
reg   [15:0] data_23_reg_1308;
reg   [15:0] data_24_reg_1313;
reg   [15:0] data_25_reg_1318;
reg   [15:0] data_26_reg_1323;
reg   [15:0] data_27_reg_1328;
reg   [15:0] data_28_reg_1333;
reg   [15:0] data_29_reg_1338;
reg   [15:0] data_30_reg_1343;
reg   [15:0] data_31_reg_1348;
reg   [15:0] data_32_reg_1353;
reg   [15:0] data_33_reg_1358;
reg   [15:0] data_34_reg_1363;
reg   [15:0] data_35_reg_1368;
reg   [15:0] data_36_reg_1373;
reg   [15:0] data_37_reg_1378;
reg   [15:0] data_38_reg_1383;
reg   [15:0] data_39_reg_1388;
reg   [15:0] data_40_reg_1393;
reg   [15:0] data_41_reg_1398;
reg   [15:0] data_42_reg_1403;
reg   [15:0] data_43_reg_1408;
reg   [15:0] data_44_reg_1413;
reg   [15:0] data_45_reg_1418;
reg   [15:0] data_46_reg_1423;
reg   [15:0] data_47_reg_1428;
reg   [15:0] data_48_reg_1433;
reg   [15:0] data_49_reg_1438;
reg   [15:0] data_50_reg_1443;
reg   [15:0] data_51_reg_1448;
reg   [15:0] data_52_reg_1453;
reg   [15:0] data_53_reg_1458;
reg   [15:0] data_54_reg_1463;
reg   [15:0] data_55_reg_1468;
reg   [15:0] data_56_reg_1473;
reg   [15:0] data_57_reg_1478;
reg   [15:0] data_58_reg_1483;
reg   [15:0] data_59_reg_1488;
reg   [15:0] data_60_reg_1493;
reg   [15:0] data_61_reg_1498;
reg   [15:0] data_62_reg_1503;
wire    grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_start;
wire    grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_done;
wire    grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_idle;
wire    grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_ready;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_0;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_1;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_2;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_3;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_4;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_5;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_6;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_7;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_8;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_9;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_10;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_11;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_12;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_13;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_14;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_15;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_16;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_17;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_18;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_19;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_20;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_21;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_22;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_23;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_24;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_25;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_26;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_27;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_28;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_29;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_30;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_31;
reg    grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_start_reg;
reg   [2:0] ap_NS_fsm;
wire    ap_NS_fsm_state2;
wire    ap_CS_fsm_state2;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_start_reg = 1'b0;
end

myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_start),
    .ap_done(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_done),
    .ap_idle(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_idle),
    .ap_ready(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_ready),
    .data_0_val(data_reg_1188),
    .data_1_val(data_1_reg_1193),
    .data_2_val(data_2_reg_1198),
    .data_3_val(data_3_reg_1203),
    .data_4_val(data_4_reg_1208),
    .data_5_val(data_5_reg_1213),
    .data_6_val(data_6_reg_1218),
    .data_7_val(data_7_reg_1223),
    .data_8_val(data_8_reg_1228),
    .data_9_val(data_9_reg_1233),
    .data_10_val(data_63_reg_1238),
    .data_11_val(data_10_reg_1243),
    .data_12_val(data_11_reg_1248),
    .data_13_val(data_12_reg_1253),
    .data_14_val(data_13_reg_1258),
    .data_15_val(data_14_reg_1263),
    .data_16_val(data_15_reg_1268),
    .data_17_val(data_16_reg_1273),
    .data_18_val(data_17_reg_1278),
    .data_19_val(data_18_reg_1283),
    .data_20_val(data_19_reg_1288),
    .data_21_val(data_20_reg_1293),
    .data_22_val(data_21_reg_1298),
    .data_23_val(data_22_reg_1303),
    .data_24_val(data_23_reg_1308),
    .data_25_val(data_24_reg_1313),
    .data_26_val(data_25_reg_1318),
    .data_27_val(data_26_reg_1323),
    .data_28_val(data_27_reg_1328),
    .data_29_val(data_28_reg_1333),
    .data_30_val(data_29_reg_1338),
    .data_31_val(data_30_reg_1343),
    .data_32_val(data_31_reg_1348),
    .data_33_val(data_32_reg_1353),
    .data_34_val(data_33_reg_1358),
    .data_35_val(data_34_reg_1363),
    .data_36_val(data_35_reg_1368),
    .data_37_val(data_36_reg_1373),
    .data_38_val(data_37_reg_1378),
    .data_39_val(data_38_reg_1383),
    .data_40_val(data_39_reg_1388),
    .data_41_val(data_40_reg_1393),
    .data_42_val(data_41_reg_1398),
    .data_43_val(data_42_reg_1403),
    .data_44_val(data_43_reg_1408),
    .data_45_val(data_44_reg_1413),
    .data_46_val(data_45_reg_1418),
    .data_47_val(data_46_reg_1423),
    .data_48_val(data_47_reg_1428),
    .data_49_val(data_48_reg_1433),
    .data_50_val(data_49_reg_1438),
    .data_51_val(data_50_reg_1443),
    .data_52_val(data_51_reg_1448),
    .data_53_val(data_52_reg_1453),
    .data_54_val(data_53_reg_1458),
    .data_55_val(data_54_reg_1463),
    .data_56_val(data_55_reg_1468),
    .data_57_val(data_56_reg_1473),
    .data_58_val(data_57_reg_1478),
    .data_59_val(data_58_reg_1483),
    .data_60_val(data_59_reg_1488),
    .data_61_val(data_60_reg_1493),
    .data_62_val(data_61_reg_1498),
    .data_63_val(data_62_reg_1503),
    .ap_return_0(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_0),
    .ap_return_1(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_1),
    .ap_return_2(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_2),
    .ap_return_3(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_3),
    .ap_return_4(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_4),
    .ap_return_5(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_5),
    .ap_return_6(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_6),
    .ap_return_7(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_7),
    .ap_return_8(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_8),
    .ap_return_9(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_9),
    .ap_return_10(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_10),
    .ap_return_11(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_11),
    .ap_return_12(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_12),
    .ap_return_13(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_13),
    .ap_return_14(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_14),
    .ap_return_15(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_15),
    .ap_return_16(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_16),
    .ap_return_17(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_17),
    .ap_return_18(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_18),
    .ap_return_19(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_19),
    .ap_return_20(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_20),
    .ap_return_21(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_21),
    .ap_return_22(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_22),
    .ap_return_23(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_23),
    .ap_return_24(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_24),
    .ap_return_25(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_25),
    .ap_return_26(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_26),
    .ap_return_27(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_27),
    .ap_return_28(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_28),
    .ap_return_29(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_29),
    .ap_return_30(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_30),
    .ap_return_31(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_31)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((layer4_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state2) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_start_reg <= 1'b1;
        end else if ((grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_ready == 1'b1)) begin
            grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        data_10_reg_1243 <= {{layer3_out_dout[191:176]}};
        data_11_reg_1248 <= {{layer3_out_dout[207:192]}};
        data_12_reg_1253 <= {{layer3_out_dout[223:208]}};
        data_13_reg_1258 <= {{layer3_out_dout[239:224]}};
        data_14_reg_1263 <= {{layer3_out_dout[255:240]}};
        data_15_reg_1268 <= {{layer3_out_dout[271:256]}};
        data_16_reg_1273 <= {{layer3_out_dout[287:272]}};
        data_17_reg_1278 <= {{layer3_out_dout[303:288]}};
        data_18_reg_1283 <= {{layer3_out_dout[319:304]}};
        data_19_reg_1288 <= {{layer3_out_dout[335:320]}};
        data_1_reg_1193 <= {{layer3_out_dout[31:16]}};
        data_20_reg_1293 <= {{layer3_out_dout[351:336]}};
        data_21_reg_1298 <= {{layer3_out_dout[367:352]}};
        data_22_reg_1303 <= {{layer3_out_dout[383:368]}};
        data_23_reg_1308 <= {{layer3_out_dout[399:384]}};
        data_24_reg_1313 <= {{layer3_out_dout[415:400]}};
        data_25_reg_1318 <= {{layer3_out_dout[431:416]}};
        data_26_reg_1323 <= {{layer3_out_dout[447:432]}};
        data_27_reg_1328 <= {{layer3_out_dout[463:448]}};
        data_28_reg_1333 <= {{layer3_out_dout[479:464]}};
        data_29_reg_1338 <= {{layer3_out_dout[495:480]}};
        data_2_reg_1198 <= {{layer3_out_dout[47:32]}};
        data_30_reg_1343 <= {{layer3_out_dout[511:496]}};
        data_31_reg_1348 <= {{layer3_out_dout[527:512]}};
        data_32_reg_1353 <= {{layer3_out_dout[543:528]}};
        data_33_reg_1358 <= {{layer3_out_dout[559:544]}};
        data_34_reg_1363 <= {{layer3_out_dout[575:560]}};
        data_35_reg_1368 <= {{layer3_out_dout[591:576]}};
        data_36_reg_1373 <= {{layer3_out_dout[607:592]}};
        data_37_reg_1378 <= {{layer3_out_dout[623:608]}};
        data_38_reg_1383 <= {{layer3_out_dout[639:624]}};
        data_39_reg_1388 <= {{layer3_out_dout[655:640]}};
        data_3_reg_1203 <= {{layer3_out_dout[63:48]}};
        data_40_reg_1393 <= {{layer3_out_dout[671:656]}};
        data_41_reg_1398 <= {{layer3_out_dout[687:672]}};
        data_42_reg_1403 <= {{layer3_out_dout[703:688]}};
        data_43_reg_1408 <= {{layer3_out_dout[719:704]}};
        data_44_reg_1413 <= {{layer3_out_dout[735:720]}};
        data_45_reg_1418 <= {{layer3_out_dout[751:736]}};
        data_46_reg_1423 <= {{layer3_out_dout[767:752]}};
        data_47_reg_1428 <= {{layer3_out_dout[783:768]}};
        data_48_reg_1433 <= {{layer3_out_dout[799:784]}};
        data_49_reg_1438 <= {{layer3_out_dout[815:800]}};
        data_4_reg_1208 <= {{layer3_out_dout[79:64]}};
        data_50_reg_1443 <= {{layer3_out_dout[831:816]}};
        data_51_reg_1448 <= {{layer3_out_dout[847:832]}};
        data_52_reg_1453 <= {{layer3_out_dout[863:848]}};
        data_53_reg_1458 <= {{layer3_out_dout[879:864]}};
        data_54_reg_1463 <= {{layer3_out_dout[895:880]}};
        data_55_reg_1468 <= {{layer3_out_dout[911:896]}};
        data_56_reg_1473 <= {{layer3_out_dout[927:912]}};
        data_57_reg_1478 <= {{layer3_out_dout[943:928]}};
        data_58_reg_1483 <= {{layer3_out_dout[959:944]}};
        data_59_reg_1488 <= {{layer3_out_dout[975:960]}};
        data_5_reg_1213 <= {{layer3_out_dout[95:80]}};
        data_60_reg_1493 <= {{layer3_out_dout[991:976]}};
        data_61_reg_1498 <= {{layer3_out_dout[1007:992]}};
        data_62_reg_1503 <= {{layer3_out_dout[1023:1008]}};
        data_63_reg_1238 <= {{layer3_out_dout[175:160]}};
        data_6_reg_1218 <= {{layer3_out_dout[111:96]}};
        data_7_reg_1223 <= {{layer3_out_dout[127:112]}};
        data_8_reg_1228 <= {{layer3_out_dout[143:128]}};
        data_9_reg_1233 <= {{layer3_out_dout[159:144]}};
        data_reg_1188 <= data_fu_357_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((layer4_out_full_n == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((layer4_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((layer4_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer3_out_blk_n = layer3_out_empty_n;
    end else begin
        layer3_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        layer3_out_read = 1'b1;
    end else begin
        layer3_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        layer4_out_blk_n = layer4_out_full_n;
    end else begin
        layer4_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((layer4_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        layer4_out_write = 1'b1;
    end else begin
        layer4_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((layer4_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_NS_fsm_state2 = ap_NS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (layer3_out_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign data_fu_357_p1 = layer3_out_dout[15:0];

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_start = grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_start_reg;

assign layer4_out_din = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_31}, {grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_30}}, {grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_29}}, {grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_28}}, {grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_27}}, {grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_26}}, {grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_25}}, {grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_24}}, {grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_23}}, {grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_22}}, {grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_21}}, 
    {grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_20}}, {grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_19}}, {grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_18}}, {grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_17}}, {grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_16}}, {grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_15}}, {grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_14}}, {grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_13}}, {grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_12}}, {grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_11}}, {grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_10}}, {grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_9}}, 
    {grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_8}}, {grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_7}}, {grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_6}}, {grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_5}}, {grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_4}}, {grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_3}}, {grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_2}}, {grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_1}}, {grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s_fu_289_ap_return_0}};

assign start_out = real_start;

endmodule //myproject_dense_array_ap_fixed_64u_array_ap_fixed_16_6_5_3_0_32u_config4_s
