// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module myproject_dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_5u_config8_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer7_out_dout,
        layer7_out_empty_n,
        layer7_out_read,
        layer7_out_num_data_valid,
        layer7_out_fifo_cap,
        layer8_out_din,
        layer8_out_full_n,
        layer8_out_write,
        layer8_out_num_data_valid,
        layer8_out_fifo_cap
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [511:0] layer7_out_dout;
input   layer7_out_empty_n;
output   layer7_out_read;
input  [1:0] layer7_out_num_data_valid;
input  [1:0] layer7_out_fifo_cap;
output  [79:0] layer8_out_din;
input   layer8_out_full_n;
output   layer8_out_write;
input  [1:0] layer8_out_num_data_valid;
input  [1:0] layer8_out_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer7_out_read;
reg layer8_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer7_out_blk_n;
reg    layer8_out_blk_n;
wire    ap_CS_fsm_state3;
wire   [15:0] data_fu_197_p1;
reg   [15:0] data_reg_541;
reg    ap_block_state1;
reg   [15:0] data_93_reg_546;
reg   [15:0] data_63_reg_551;
reg   [15:0] data_64_reg_556;
reg   [15:0] data_65_reg_561;
reg   [15:0] data_66_reg_566;
reg   [15:0] data_67_reg_571;
reg   [15:0] data_68_reg_576;
reg   [15:0] data_69_reg_581;
reg   [15:0] data_70_reg_586;
reg   [15:0] data_71_reg_591;
reg   [15:0] data_72_reg_596;
reg   [15:0] data_73_reg_601;
reg   [15:0] data_74_reg_606;
reg   [15:0] data_75_reg_611;
reg   [15:0] data_76_reg_616;
reg   [15:0] data_77_reg_621;
reg   [15:0] data_78_reg_626;
reg   [15:0] data_79_reg_631;
reg   [15:0] data_80_reg_636;
reg   [15:0] data_81_reg_641;
reg   [15:0] data_82_reg_646;
reg   [15:0] data_83_reg_651;
reg   [15:0] data_84_reg_656;
reg   [15:0] data_85_reg_661;
reg   [15:0] data_86_reg_666;
reg   [15:0] data_87_reg_671;
reg   [15:0] data_88_reg_676;
reg   [15:0] data_89_reg_681;
reg   [15:0] data_90_reg_686;
reg   [15:0] data_91_reg_691;
reg   [15:0] data_92_reg_696;
reg   [15:0] res_reg_701;
wire    ap_CS_fsm_state2;
reg   [15:0] res_1_reg_706;
reg   [15:0] res_2_reg_711;
reg   [15:0] res_3_reg_716;
reg   [15:0] res_4_reg_721;
wire    call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_161_ap_ready;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_161_ap_return_0;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_161_ap_return_1;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_161_ap_return_2;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_161_ap_return_3;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_161_ap_return_4;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
end

myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_161(
    .ap_ready(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_161_ap_ready),
    .data_0_val(data_reg_541),
    .data_1_val(data_93_reg_546),
    .data_2_val(data_63_reg_551),
    .data_3_val(data_64_reg_556),
    .data_4_val(data_65_reg_561),
    .data_5_val(data_66_reg_566),
    .data_6_val(data_67_reg_571),
    .data_7_val(data_68_reg_576),
    .data_8_val(data_69_reg_581),
    .data_9_val(data_70_reg_586),
    .data_10_val(data_71_reg_591),
    .data_11_val(data_72_reg_596),
    .data_12_val(data_73_reg_601),
    .data_13_val(data_74_reg_606),
    .data_14_val(data_75_reg_611),
    .data_15_val(data_76_reg_616),
    .data_16_val(data_77_reg_621),
    .data_17_val(data_78_reg_626),
    .data_18_val(data_79_reg_631),
    .data_19_val(data_80_reg_636),
    .data_20_val(data_81_reg_641),
    .data_21_val(data_82_reg_646),
    .data_22_val(data_83_reg_651),
    .data_23_val(data_84_reg_656),
    .data_24_val(data_85_reg_661),
    .data_25_val(data_86_reg_666),
    .data_26_val(data_87_reg_671),
    .data_27_val(data_88_reg_676),
    .data_28_val(data_89_reg_681),
    .data_29_val(data_90_reg_686),
    .data_30_val(data_91_reg_691),
    .data_31_val(data_92_reg_696),
    .ap_return_0(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_161_ap_return_0),
    .ap_return_1(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_161_ap_return_1),
    .ap_return_2(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_161_ap_return_2),
    .ap_return_3(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_161_ap_return_3),
    .ap_return_4(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_161_ap_return_4),
    .ap_rst(ap_rst)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((layer8_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        data_63_reg_551 <= {{layer7_out_dout[47:32]}};
        data_64_reg_556 <= {{layer7_out_dout[63:48]}};
        data_65_reg_561 <= {{layer7_out_dout[79:64]}};
        data_66_reg_566 <= {{layer7_out_dout[95:80]}};
        data_67_reg_571 <= {{layer7_out_dout[111:96]}};
        data_68_reg_576 <= {{layer7_out_dout[127:112]}};
        data_69_reg_581 <= {{layer7_out_dout[143:128]}};
        data_70_reg_586 <= {{layer7_out_dout[159:144]}};
        data_71_reg_591 <= {{layer7_out_dout[175:160]}};
        data_72_reg_596 <= {{layer7_out_dout[191:176]}};
        data_73_reg_601 <= {{layer7_out_dout[207:192]}};
        data_74_reg_606 <= {{layer7_out_dout[223:208]}};
        data_75_reg_611 <= {{layer7_out_dout[239:224]}};
        data_76_reg_616 <= {{layer7_out_dout[255:240]}};
        data_77_reg_621 <= {{layer7_out_dout[271:256]}};
        data_78_reg_626 <= {{layer7_out_dout[287:272]}};
        data_79_reg_631 <= {{layer7_out_dout[303:288]}};
        data_80_reg_636 <= {{layer7_out_dout[319:304]}};
        data_81_reg_641 <= {{layer7_out_dout[335:320]}};
        data_82_reg_646 <= {{layer7_out_dout[351:336]}};
        data_83_reg_651 <= {{layer7_out_dout[367:352]}};
        data_84_reg_656 <= {{layer7_out_dout[383:368]}};
        data_85_reg_661 <= {{layer7_out_dout[399:384]}};
        data_86_reg_666 <= {{layer7_out_dout[415:400]}};
        data_87_reg_671 <= {{layer7_out_dout[431:416]}};
        data_88_reg_676 <= {{layer7_out_dout[447:432]}};
        data_89_reg_681 <= {{layer7_out_dout[463:448]}};
        data_90_reg_686 <= {{layer7_out_dout[479:464]}};
        data_91_reg_691 <= {{layer7_out_dout[495:480]}};
        data_92_reg_696 <= {{layer7_out_dout[511:496]}};
        data_93_reg_546 <= {{layer7_out_dout[31:16]}};
        data_reg_541 <= data_fu_197_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        res_1_reg_706 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_161_ap_return_1;
        res_2_reg_711 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_161_ap_return_2;
        res_3_reg_716 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_161_ap_return_3;
        res_4_reg_721 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_161_ap_return_4;
        res_reg_701 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_161_ap_return_0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((layer8_out_full_n == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((layer8_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((layer8_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer7_out_blk_n = layer7_out_empty_n;
    end else begin
        layer7_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        layer7_out_read = 1'b1;
    end else begin
        layer7_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        layer8_out_blk_n = layer8_out_full_n;
    end else begin
        layer8_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((layer8_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        layer8_out_write = 1'b1;
    end else begin
        layer8_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((layer8_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (layer7_out_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign data_fu_197_p1 = layer7_out_dout[15:0];

assign layer8_out_din = {{{{{res_4_reg_721}, {res_3_reg_716}}, {res_2_reg_711}}, {res_1_reg_706}}, {res_reg_701}};

assign start_out = real_start;

endmodule //myproject_dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_5u_config8_s
