// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module myproject_softmax_stable_array_array_ap_fixed_16_6_5_3_0_5u_softmax_config9_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        layer8_out_dout,
        layer8_out_empty_n,
        layer8_out_read,
        layer8_out_num_data_valid,
        layer8_out_fifo_cap,
        layer9_out_TDATA,
        layer9_out_TVALID,
        layer9_out_TREADY
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [79:0] layer8_out_dout;
input   layer8_out_empty_n;
output   layer8_out_read;
input  [1:0] layer8_out_num_data_valid;
input  [1:0] layer8_out_fifo_cap;
output  [79:0] layer9_out_TDATA;
output   layer9_out_TVALID;
input   layer9_out_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg layer8_out_read;
reg layer9_out_TVALID;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [9:0] exp_table_address0;
wire   [10:0] exp_table_q0;
wire   [9:0] exp_table_address1;
wire   [10:0] exp_table_q1;
wire   [9:0] exp_table_address2;
wire   [10:0] exp_table_q2;
wire   [9:0] exp_table_address3;
wire   [10:0] exp_table_q3;
wire   [9:0] exp_table_address4;
wire   [10:0] exp_table_q4;
wire   [9:0] invert_table_address0;
wire   [17:0] invert_table_q0;
reg    layer8_out_blk_n;
reg    layer9_out_TDATA_blk_n;
wire    ap_CS_fsm_state4;
reg   [9:0] tmp_5_reg_729;
reg   [9:0] tmp_7_reg_734;
reg   [9:0] tmp_9_reg_739;
reg   [9:0] tmp_s_reg_744;
reg   [9:0] tmp_4_reg_749;
wire    ap_CS_fsm_state2;
reg   [10:0] a_reg_779;
wire    ap_CS_fsm_state3;
reg   [10:0] b_reg_784;
reg   [10:0] a_1_reg_789;
reg   [10:0] b_1_reg_794;
reg   [10:0] b_2_reg_799;
wire   [63:0] zext_ln223_fu_548_p1;
wire   [63:0] zext_ln223_1_fu_552_p1;
wire   [63:0] zext_ln223_2_fu_556_p1;
wire   [63:0] zext_ln223_3_fu_560_p1;
wire   [63:0] zext_ln223_4_fu_564_p1;
wire   [63:0] zext_ln232_fu_630_p1;
reg    ap_block_state1;
reg    exp_table_ce4_local;
reg    exp_table_ce3_local;
reg    exp_table_ce2_local;
reg    exp_table_ce1_local;
reg    exp_table_ce0_local;
reg    invert_table_ce0_local;
wire  signed [17:0] mul_ln241_4_fu_185_p0;
wire  signed [25:0] sext_ln241_fu_635_p1;
wire   [10:0] mul_ln241_4_fu_185_p1;
wire  signed [17:0] mul_ln241_fu_186_p0;
wire   [10:0] mul_ln241_fu_186_p1;
wire  signed [17:0] mul_ln241_3_fu_187_p0;
wire   [10:0] mul_ln241_3_fu_187_p1;
wire  signed [17:0] mul_ln241_2_fu_188_p0;
wire   [10:0] mul_ln241_2_fu_188_p1;
wire  signed [17:0] mul_ln241_1_fu_189_p0;
wire   [10:0] mul_ln241_1_fu_189_p1;
wire   [15:0] trunc_ln198_fu_296_p1;
wire   [15:0] trunc_ln198_1_fu_300_p4;
wire   [0:0] icmp_ln66_fu_340_p2;
wire   [0:0] xor_ln66_fu_346_p2;
wire   [15:0] trunc_ln198_2_fu_310_p4;
wire   [15:0] trunc_ln198_3_fu_320_p4;
wire   [0:0] icmp_ln66_1_fu_360_p2;
wire   [0:0] xor_ln66_1_fu_366_p2;
wire   [15:0] select_ln66_fu_352_p3;
wire   [15:0] select_ln66_1_fu_372_p3;
wire   [0:0] icmp_ln66_2_fu_380_p2;
wire   [0:0] xor_ln66_2_fu_386_p2;
wire   [15:0] select_ln66_2_fu_392_p3;
wire   [15:0] trunc_ln198_4_fu_330_p4;
wire   [0:0] icmp_ln66_3_fu_400_p2;
wire   [0:0] xor_ln66_3_fu_406_p2;
wire   [14:0] trunc_ln66_fu_412_p1;
wire   [14:0] tmp_fu_416_p4;
wire   [14:0] select_ln66_3_fu_426_p3;
wire   [14:0] trunc_ln213_fu_434_p1;
wire   [14:0] trunc_ln213_2_fu_444_p4;
wire   [14:0] trunc_ln213_3_fu_460_p4;
wire   [14:0] trunc_ln213_4_fu_476_p4;
wire   [14:0] x_fu_438_p2;
wire   [14:0] x_1_fu_454_p2;
wire   [14:0] x_2_fu_470_p2;
wire   [14:0] x_3_fu_486_p2;
wire   [14:0] x_4_fu_492_p2;
wire   [11:0] zext_ln141_fu_568_p1;
wire   [11:0] zext_ln141_2_fu_576_p1;
wire   [11:0] add_ln51_fu_588_p2;
wire   [11:0] zext_ln141_1_fu_572_p1;
wire   [11:0] add_ln51_1_fu_594_p2;
wire   [11:0] zext_ln141_3_fu_580_p1;
wire   [11:0] zext_ln51_fu_584_p1;
wire   [11:0] add_ln51_2_fu_604_p2;
wire   [12:0] zext_ln51_2_fu_610_p1;
wire   [12:0] zext_ln51_1_fu_600_p1;
wire   [12:0] add_ln51_3_fu_614_p2;
wire   [4:0] tmp_1_fu_620_p4;
wire   [25:0] mul_ln241_fu_186_p2;
wire   [25:0] mul_ln241_1_fu_189_p2;
wire   [25:0] mul_ln241_2_fu_188_p2;
wire   [25:0] mul_ln241_3_fu_187_p2;
wire   [25:0] mul_ln241_4_fu_185_p2;
wire   [15:0] trunc_ln241_4_fu_704_p4;
wire   [15:0] trunc_ln241_3_fu_690_p4;
wire   [15:0] trunc_ln241_2_fu_676_p4;
wire   [15:0] trunc_ln241_1_fu_662_p4;
wire   [15:0] trunc_ln3_fu_648_p4;
wire    ap_CS_fsm_state5;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire   [25:0] mul_ln241_1_fu_189_p10;
wire   [25:0] mul_ln241_2_fu_188_p10;
wire   [25:0] mul_ln241_3_fu_187_p10;
wire   [25:0] mul_ln241_4_fu_185_p10;
wire   [25:0] mul_ln241_fu_186_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
end

myproject_softmax_stable_array_array_ap_fixed_16_6_5_3_0_5u_softmax_config9_s_exp_tablebkb #(
    .DataWidth( 11 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
exp_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(exp_table_address0),
    .ce0(exp_table_ce0_local),
    .q0(exp_table_q0),
    .address1(exp_table_address1),
    .ce1(exp_table_ce1_local),
    .q1(exp_table_q1),
    .address2(exp_table_address2),
    .ce2(exp_table_ce2_local),
    .q2(exp_table_q2),
    .address3(exp_table_address3),
    .ce3(exp_table_ce3_local),
    .q3(exp_table_q3),
    .address4(exp_table_address4),
    .ce4(exp_table_ce4_local),
    .q4(exp_table_q4)
);

myproject_softmax_stable_array_array_ap_fixed_16_6_5_3_0_5u_softmax_config9_s_invert_tacud #(
    .DataWidth( 18 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
invert_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(invert_table_address0),
    .ce0(invert_table_ce0_local),
    .q0(invert_table_q0)
);

myproject_mul_18s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_18s_11ns_26_1_1_U3507(
    .din0(mul_ln241_4_fu_185_p0),
    .din1(mul_ln241_4_fu_185_p1),
    .dout(mul_ln241_4_fu_185_p2)
);

myproject_mul_18s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_18s_11ns_26_1_1_U3508(
    .din0(mul_ln241_fu_186_p0),
    .din1(mul_ln241_fu_186_p1),
    .dout(mul_ln241_fu_186_p2)
);

myproject_mul_18s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_18s_11ns_26_1_1_U3509(
    .din0(mul_ln241_3_fu_187_p0),
    .din1(mul_ln241_3_fu_187_p1),
    .dout(mul_ln241_3_fu_187_p2)
);

myproject_mul_18s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_18s_11ns_26_1_1_U3510(
    .din0(mul_ln241_2_fu_188_p0),
    .din1(mul_ln241_2_fu_188_p1),
    .dout(mul_ln241_2_fu_188_p2)
);

myproject_mul_18s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_18s_11ns_26_1_1_U3511(
    .din0(mul_ln241_1_fu_189_p0),
    .din1(mul_ln241_1_fu_189_p1),
    .dout(mul_ln241_1_fu_189_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        a_1_reg_789 <= exp_table_q2;
        a_reg_779 <= exp_table_q4;
        b_1_reg_794 <= exp_table_q1;
        b_2_reg_799 <= exp_table_q0;
        b_reg_784 <= exp_table_q3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        tmp_4_reg_749 <= {{x_4_fu_492_p2[14:5]}};
        tmp_5_reg_729 <= {{x_fu_438_p2[14:5]}};
        tmp_7_reg_734 <= {{x_1_fu_454_p2[14:5]}};
        tmp_9_reg_739 <= {{x_2_fu_470_p2[14:5]}};
        tmp_s_reg_744 <= {{x_3_fu_486_p2[14:5]}};
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((layer9_out_TREADY == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        exp_table_ce0_local = 1'b1;
    end else begin
        exp_table_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        exp_table_ce1_local = 1'b1;
    end else begin
        exp_table_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        exp_table_ce2_local = 1'b1;
    end else begin
        exp_table_ce2_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        exp_table_ce3_local = 1'b1;
    end else begin
        exp_table_ce3_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        exp_table_ce4_local = 1'b1;
    end else begin
        exp_table_ce4_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        invert_table_ce0_local = 1'b1;
    end else begin
        invert_table_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        layer8_out_blk_n = layer8_out_empty_n;
    end else begin
        layer8_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        layer8_out_read = 1'b1;
    end else begin
        layer8_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        layer9_out_TDATA_blk_n = layer9_out_TREADY;
    end else begin
        layer9_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((layer9_out_TREADY == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        layer9_out_TVALID = 1'b1;
    end else begin
        layer9_out_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((layer9_out_TREADY == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln51_1_fu_594_p2 = (add_ln51_fu_588_p2 + zext_ln141_1_fu_572_p1);

assign add_ln51_2_fu_604_p2 = (zext_ln141_3_fu_580_p1 + zext_ln51_fu_584_p1);

assign add_ln51_3_fu_614_p2 = (zext_ln51_2_fu_610_p1 + zext_ln51_1_fu_600_p1);

assign add_ln51_fu_588_p2 = (zext_ln141_fu_568_p1 + zext_ln141_2_fu_576_p1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state1 = ((layer8_out_empty_n == 1'b0) | (ap_start == 1'b0));
end

assign exp_table_address0 = zext_ln223_4_fu_564_p1;

assign exp_table_address1 = zext_ln223_3_fu_560_p1;

assign exp_table_address2 = zext_ln223_2_fu_556_p1;

assign exp_table_address3 = zext_ln223_1_fu_552_p1;

assign exp_table_address4 = zext_ln223_fu_548_p1;

assign icmp_ln66_1_fu_360_p2 = (($signed(trunc_ln198_2_fu_310_p4) < $signed(trunc_ln198_3_fu_320_p4)) ? 1'b1 : 1'b0);

assign icmp_ln66_2_fu_380_p2 = (($signed(select_ln66_fu_352_p3) < $signed(select_ln66_1_fu_372_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_3_fu_400_p2 = (($signed(select_ln66_2_fu_392_p3) < $signed(trunc_ln198_4_fu_330_p4)) ? 1'b1 : 1'b0);

assign icmp_ln66_fu_340_p2 = (($signed(trunc_ln198_fu_296_p1) < $signed(trunc_ln198_1_fu_300_p4)) ? 1'b1 : 1'b0);

assign invert_table_address0 = zext_ln232_fu_630_p1;

assign layer9_out_TDATA = {{{{{trunc_ln241_4_fu_704_p4}, {trunc_ln241_3_fu_690_p4}}, {trunc_ln241_2_fu_676_p4}}, {trunc_ln241_1_fu_662_p4}}, {trunc_ln3_fu_648_p4}};

assign mul_ln241_1_fu_189_p0 = sext_ln241_fu_635_p1;

assign mul_ln241_1_fu_189_p1 = mul_ln241_1_fu_189_p10;

assign mul_ln241_1_fu_189_p10 = b_reg_784;

assign mul_ln241_2_fu_188_p0 = sext_ln241_fu_635_p1;

assign mul_ln241_2_fu_188_p1 = mul_ln241_2_fu_188_p10;

assign mul_ln241_2_fu_188_p10 = a_1_reg_789;

assign mul_ln241_3_fu_187_p0 = sext_ln241_fu_635_p1;

assign mul_ln241_3_fu_187_p1 = mul_ln241_3_fu_187_p10;

assign mul_ln241_3_fu_187_p10 = b_1_reg_794;

assign mul_ln241_4_fu_185_p0 = sext_ln241_fu_635_p1;

assign mul_ln241_4_fu_185_p1 = mul_ln241_4_fu_185_p10;

assign mul_ln241_4_fu_185_p10 = b_2_reg_799;

assign mul_ln241_fu_186_p0 = sext_ln241_fu_635_p1;

assign mul_ln241_fu_186_p1 = mul_ln241_fu_186_p10;

assign mul_ln241_fu_186_p10 = a_reg_779;

assign select_ln66_1_fu_372_p3 = ((xor_ln66_1_fu_366_p2[0:0] == 1'b1) ? trunc_ln198_2_fu_310_p4 : trunc_ln198_3_fu_320_p4);

assign select_ln66_2_fu_392_p3 = ((xor_ln66_2_fu_386_p2[0:0] == 1'b1) ? select_ln66_fu_352_p3 : select_ln66_1_fu_372_p3);

assign select_ln66_3_fu_426_p3 = ((xor_ln66_3_fu_406_p2[0:0] == 1'b1) ? trunc_ln66_fu_412_p1 : tmp_fu_416_p4);

assign select_ln66_fu_352_p3 = ((xor_ln66_fu_346_p2[0:0] == 1'b1) ? trunc_ln198_fu_296_p1 : trunc_ln198_1_fu_300_p4);

assign sext_ln241_fu_635_p1 = $signed(invert_table_q0);

assign tmp_1_fu_620_p4 = {{add_ln51_3_fu_614_p2[12:8]}};

assign tmp_fu_416_p4 = {{layer8_out_dout[78:64]}};

assign trunc_ln198_1_fu_300_p4 = {{layer8_out_dout[31:16]}};

assign trunc_ln198_2_fu_310_p4 = {{layer8_out_dout[47:32]}};

assign trunc_ln198_3_fu_320_p4 = {{layer8_out_dout[63:48]}};

assign trunc_ln198_4_fu_330_p4 = {{layer8_out_dout[79:64]}};

assign trunc_ln198_fu_296_p1 = layer8_out_dout[15:0];

assign trunc_ln213_2_fu_444_p4 = {{layer8_out_dout[30:16]}};

assign trunc_ln213_3_fu_460_p4 = {{layer8_out_dout[46:32]}};

assign trunc_ln213_4_fu_476_p4 = {{layer8_out_dout[62:48]}};

assign trunc_ln213_fu_434_p1 = layer8_out_dout[14:0];

assign trunc_ln241_1_fu_662_p4 = {{mul_ln241_1_fu_189_p2[25:10]}};

assign trunc_ln241_2_fu_676_p4 = {{mul_ln241_2_fu_188_p2[25:10]}};

assign trunc_ln241_3_fu_690_p4 = {{mul_ln241_3_fu_187_p2[25:10]}};

assign trunc_ln241_4_fu_704_p4 = {{mul_ln241_4_fu_185_p2[25:10]}};

assign trunc_ln3_fu_648_p4 = {{mul_ln241_fu_186_p2[25:10]}};

assign trunc_ln66_fu_412_p1 = select_ln66_2_fu_392_p3[14:0];

assign x_1_fu_454_p2 = (select_ln66_3_fu_426_p3 - trunc_ln213_2_fu_444_p4);

assign x_2_fu_470_p2 = (select_ln66_3_fu_426_p3 - trunc_ln213_3_fu_460_p4);

assign x_3_fu_486_p2 = (select_ln66_3_fu_426_p3 - trunc_ln213_4_fu_476_p4);

assign x_4_fu_492_p2 = (select_ln66_3_fu_426_p3 - tmp_fu_416_p4);

assign x_fu_438_p2 = (select_ln66_3_fu_426_p3 - trunc_ln213_fu_434_p1);

assign xor_ln66_1_fu_366_p2 = (icmp_ln66_1_fu_360_p2 ^ 1'd1);

assign xor_ln66_2_fu_386_p2 = (icmp_ln66_2_fu_380_p2 ^ 1'd1);

assign xor_ln66_3_fu_406_p2 = (icmp_ln66_3_fu_400_p2 ^ 1'd1);

assign xor_ln66_fu_346_p2 = (icmp_ln66_fu_340_p2 ^ 1'd1);

assign zext_ln141_1_fu_572_p1 = exp_table_q3;

assign zext_ln141_2_fu_576_p1 = exp_table_q2;

assign zext_ln141_3_fu_580_p1 = exp_table_q1;

assign zext_ln141_fu_568_p1 = exp_table_q4;

assign zext_ln223_1_fu_552_p1 = tmp_7_reg_734;

assign zext_ln223_2_fu_556_p1 = tmp_9_reg_739;

assign zext_ln223_3_fu_560_p1 = tmp_s_reg_744;

assign zext_ln223_4_fu_564_p1 = tmp_4_reg_749;

assign zext_ln223_fu_548_p1 = tmp_5_reg_729;

assign zext_ln232_fu_630_p1 = tmp_1_fu_620_p4;

assign zext_ln51_1_fu_600_p1 = add_ln51_1_fu_594_p2;

assign zext_ln51_2_fu_610_p1 = add_ln51_2_fu_604_p2;

assign zext_ln51_fu_584_p1 = exp_table_q0;

endmodule //myproject_softmax_stable_array_array_ap_fixed_16_6_5_3_0_5u_softmax_config9_s
