// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module myproject_relu_array_ap_fixed_64u_array_ap_fixed_16_6_5_3_0_64u_relu_config3_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer2_out_dout,
        layer2_out_empty_n,
        layer2_out_read,
        layer2_out_num_data_valid,
        layer2_out_fifo_cap,
        layer3_out_din,
        layer3_out_full_n,
        layer3_out_write,
        layer3_out_num_data_valid,
        layer3_out_fifo_cap
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [1023:0] layer2_out_dout;
input   layer2_out_empty_n;
output   layer2_out_read;
input  [1:0] layer2_out_num_data_valid;
input  [1:0] layer2_out_fifo_cap;
output  [1023:0] layer3_out_din;
input   layer3_out_full_n;
output   layer3_out_write;
input  [1:0] layer3_out_num_data_valid;
input  [1:0] layer3_out_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer2_out_read;
reg layer3_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer2_out_blk_n;
reg    layer3_out_blk_n;
reg    ap_block_state1;
wire   [15:0] trunc_ln44_fu_419_p1;
wire   [0:0] icmp_ln51_fu_1687_p2;
wire   [14:0] trunc_ln44_126_fu_423_p1;
wire   [14:0] select_ln51_fu_1693_p3;
wire   [15:0] trunc_ln44_1_fu_427_p4;
wire   [0:0] icmp_ln51_1_fu_1705_p2;
wire   [14:0] trunc_ln44_s_fu_437_p4;
wire   [14:0] select_ln51_1_fu_1711_p3;
wire   [15:0] trunc_ln44_2_fu_447_p4;
wire   [0:0] icmp_ln51_2_fu_1723_p2;
wire   [14:0] trunc_ln44_64_fu_457_p4;
wire   [14:0] select_ln51_2_fu_1729_p3;
wire   [15:0] trunc_ln44_3_fu_467_p4;
wire   [0:0] icmp_ln51_3_fu_1741_p2;
wire   [14:0] trunc_ln44_65_fu_477_p4;
wire   [14:0] select_ln51_3_fu_1747_p3;
wire   [15:0] trunc_ln44_4_fu_487_p4;
wire   [0:0] icmp_ln51_4_fu_1759_p2;
wire   [14:0] trunc_ln44_66_fu_497_p4;
wire   [14:0] select_ln51_4_fu_1765_p3;
wire   [15:0] trunc_ln44_5_fu_507_p4;
wire   [0:0] icmp_ln51_5_fu_1777_p2;
wire   [14:0] trunc_ln44_67_fu_517_p4;
wire   [14:0] select_ln51_5_fu_1783_p3;
wire   [15:0] trunc_ln44_6_fu_527_p4;
wire   [0:0] icmp_ln51_6_fu_1795_p2;
wire   [14:0] trunc_ln44_68_fu_537_p4;
wire   [14:0] select_ln51_6_fu_1801_p3;
wire   [15:0] trunc_ln44_7_fu_547_p4;
wire   [0:0] icmp_ln51_7_fu_1813_p2;
wire   [14:0] trunc_ln44_69_fu_557_p4;
wire   [14:0] select_ln51_7_fu_1819_p3;
wire   [15:0] trunc_ln44_8_fu_567_p4;
wire   [0:0] icmp_ln51_8_fu_1831_p2;
wire   [14:0] trunc_ln44_70_fu_577_p4;
wire   [14:0] select_ln51_8_fu_1837_p3;
wire   [15:0] trunc_ln44_9_fu_587_p4;
wire   [0:0] icmp_ln51_9_fu_1849_p2;
wire   [14:0] trunc_ln44_71_fu_597_p4;
wire   [14:0] select_ln51_9_fu_1855_p3;
wire   [15:0] trunc_ln44_10_fu_607_p4;
wire   [0:0] icmp_ln51_10_fu_1867_p2;
wire   [14:0] trunc_ln44_72_fu_617_p4;
wire   [14:0] select_ln51_10_fu_1873_p3;
wire   [15:0] trunc_ln44_11_fu_627_p4;
wire   [0:0] icmp_ln51_11_fu_1885_p2;
wire   [14:0] trunc_ln44_73_fu_637_p4;
wire   [14:0] select_ln51_11_fu_1891_p3;
wire   [15:0] trunc_ln44_12_fu_647_p4;
wire   [0:0] icmp_ln51_12_fu_1903_p2;
wire   [14:0] trunc_ln44_74_fu_657_p4;
wire   [14:0] select_ln51_12_fu_1909_p3;
wire   [15:0] trunc_ln44_13_fu_667_p4;
wire   [0:0] icmp_ln51_13_fu_1921_p2;
wire   [14:0] trunc_ln44_75_fu_677_p4;
wire   [14:0] select_ln51_13_fu_1927_p3;
wire   [15:0] trunc_ln44_14_fu_687_p4;
wire   [0:0] icmp_ln51_14_fu_1939_p2;
wire   [14:0] trunc_ln44_76_fu_697_p4;
wire   [14:0] select_ln51_14_fu_1945_p3;
wire   [15:0] trunc_ln44_15_fu_707_p4;
wire   [0:0] icmp_ln51_15_fu_1957_p2;
wire   [14:0] trunc_ln44_77_fu_717_p4;
wire   [14:0] select_ln51_15_fu_1963_p3;
wire   [15:0] trunc_ln44_16_fu_727_p4;
wire   [0:0] icmp_ln51_16_fu_1975_p2;
wire   [14:0] trunc_ln44_78_fu_737_p4;
wire   [14:0] select_ln51_16_fu_1981_p3;
wire   [15:0] trunc_ln44_17_fu_747_p4;
wire   [0:0] icmp_ln51_17_fu_1993_p2;
wire   [14:0] trunc_ln44_79_fu_757_p4;
wire   [14:0] select_ln51_17_fu_1999_p3;
wire   [15:0] trunc_ln44_18_fu_767_p4;
wire   [0:0] icmp_ln51_18_fu_2011_p2;
wire   [14:0] trunc_ln44_80_fu_777_p4;
wire   [14:0] select_ln51_18_fu_2017_p3;
wire   [15:0] trunc_ln44_19_fu_787_p4;
wire   [0:0] icmp_ln51_19_fu_2029_p2;
wire   [14:0] trunc_ln44_81_fu_797_p4;
wire   [14:0] select_ln51_19_fu_2035_p3;
wire   [15:0] trunc_ln44_20_fu_807_p4;
wire   [0:0] icmp_ln51_20_fu_2047_p2;
wire   [14:0] trunc_ln44_82_fu_817_p4;
wire   [14:0] select_ln51_20_fu_2053_p3;
wire   [15:0] trunc_ln44_21_fu_827_p4;
wire   [0:0] icmp_ln51_21_fu_2065_p2;
wire   [14:0] trunc_ln44_83_fu_837_p4;
wire   [14:0] select_ln51_21_fu_2071_p3;
wire   [15:0] trunc_ln44_22_fu_847_p4;
wire   [0:0] icmp_ln51_22_fu_2083_p2;
wire   [14:0] trunc_ln44_84_fu_857_p4;
wire   [14:0] select_ln51_22_fu_2089_p3;
wire   [15:0] trunc_ln44_23_fu_867_p4;
wire   [0:0] icmp_ln51_23_fu_2101_p2;
wire   [14:0] trunc_ln44_85_fu_877_p4;
wire   [14:0] select_ln51_23_fu_2107_p3;
wire   [15:0] trunc_ln44_24_fu_887_p4;
wire   [0:0] icmp_ln51_24_fu_2119_p2;
wire   [14:0] trunc_ln44_86_fu_897_p4;
wire   [14:0] select_ln51_24_fu_2125_p3;
wire   [15:0] trunc_ln44_25_fu_907_p4;
wire   [0:0] icmp_ln51_25_fu_2137_p2;
wire   [14:0] trunc_ln44_87_fu_917_p4;
wire   [14:0] select_ln51_25_fu_2143_p3;
wire   [15:0] trunc_ln44_26_fu_927_p4;
wire   [0:0] icmp_ln51_26_fu_2155_p2;
wire   [14:0] trunc_ln44_88_fu_937_p4;
wire   [14:0] select_ln51_26_fu_2161_p3;
wire   [15:0] trunc_ln44_27_fu_947_p4;
wire   [0:0] icmp_ln51_27_fu_2173_p2;
wire   [14:0] trunc_ln44_89_fu_957_p4;
wire   [14:0] select_ln51_27_fu_2179_p3;
wire   [15:0] trunc_ln44_28_fu_967_p4;
wire   [0:0] icmp_ln51_28_fu_2191_p2;
wire   [14:0] trunc_ln44_90_fu_977_p4;
wire   [14:0] select_ln51_28_fu_2197_p3;
wire   [15:0] trunc_ln44_29_fu_987_p4;
wire   [0:0] icmp_ln51_29_fu_2209_p2;
wire   [14:0] trunc_ln44_91_fu_997_p4;
wire   [14:0] select_ln51_29_fu_2215_p3;
wire   [15:0] trunc_ln44_30_fu_1007_p4;
wire   [0:0] icmp_ln51_30_fu_2227_p2;
wire   [14:0] trunc_ln44_92_fu_1017_p4;
wire   [14:0] select_ln51_30_fu_2233_p3;
wire   [15:0] trunc_ln44_31_fu_1027_p4;
wire   [0:0] icmp_ln51_31_fu_2245_p2;
wire   [14:0] trunc_ln44_93_fu_1037_p4;
wire   [14:0] select_ln51_31_fu_2251_p3;
wire   [15:0] trunc_ln44_32_fu_1047_p4;
wire   [0:0] icmp_ln51_32_fu_2263_p2;
wire   [14:0] trunc_ln44_94_fu_1057_p4;
wire   [14:0] select_ln51_32_fu_2269_p3;
wire   [15:0] trunc_ln44_33_fu_1067_p4;
wire   [0:0] icmp_ln51_33_fu_2281_p2;
wire   [14:0] trunc_ln44_95_fu_1077_p4;
wire   [14:0] select_ln51_33_fu_2287_p3;
wire   [15:0] trunc_ln44_34_fu_1087_p4;
wire   [0:0] icmp_ln51_34_fu_2299_p2;
wire   [14:0] trunc_ln44_96_fu_1097_p4;
wire   [14:0] select_ln51_34_fu_2305_p3;
wire   [15:0] trunc_ln44_35_fu_1107_p4;
wire   [0:0] icmp_ln51_35_fu_2317_p2;
wire   [14:0] trunc_ln44_97_fu_1117_p4;
wire   [14:0] select_ln51_35_fu_2323_p3;
wire   [15:0] trunc_ln44_36_fu_1127_p4;
wire   [0:0] icmp_ln51_36_fu_2335_p2;
wire   [14:0] trunc_ln44_98_fu_1137_p4;
wire   [14:0] select_ln51_36_fu_2341_p3;
wire   [15:0] trunc_ln44_37_fu_1147_p4;
wire   [0:0] icmp_ln51_37_fu_2353_p2;
wire   [14:0] trunc_ln44_99_fu_1157_p4;
wire   [14:0] select_ln51_37_fu_2359_p3;
wire   [15:0] trunc_ln44_38_fu_1167_p4;
wire   [0:0] icmp_ln51_38_fu_2371_p2;
wire   [14:0] trunc_ln44_100_fu_1177_p4;
wire   [14:0] select_ln51_38_fu_2377_p3;
wire   [15:0] trunc_ln44_39_fu_1187_p4;
wire   [0:0] icmp_ln51_39_fu_2389_p2;
wire   [14:0] trunc_ln44_101_fu_1197_p4;
wire   [14:0] select_ln51_39_fu_2395_p3;
wire   [15:0] trunc_ln44_40_fu_1207_p4;
wire   [0:0] icmp_ln51_40_fu_2407_p2;
wire   [14:0] trunc_ln44_102_fu_1217_p4;
wire   [14:0] select_ln51_40_fu_2413_p3;
wire   [15:0] trunc_ln44_41_fu_1227_p4;
wire   [0:0] icmp_ln51_41_fu_2425_p2;
wire   [14:0] trunc_ln44_103_fu_1237_p4;
wire   [14:0] select_ln51_41_fu_2431_p3;
wire   [15:0] trunc_ln44_42_fu_1247_p4;
wire   [0:0] icmp_ln51_42_fu_2443_p2;
wire   [14:0] trunc_ln44_104_fu_1257_p4;
wire   [14:0] select_ln51_42_fu_2449_p3;
wire   [15:0] trunc_ln44_43_fu_1267_p4;
wire   [0:0] icmp_ln51_43_fu_2461_p2;
wire   [14:0] trunc_ln44_105_fu_1277_p4;
wire   [14:0] select_ln51_43_fu_2467_p3;
wire   [15:0] trunc_ln44_44_fu_1287_p4;
wire   [0:0] icmp_ln51_44_fu_2479_p2;
wire   [14:0] trunc_ln44_106_fu_1297_p4;
wire   [14:0] select_ln51_44_fu_2485_p3;
wire   [15:0] trunc_ln44_45_fu_1307_p4;
wire   [0:0] icmp_ln51_45_fu_2497_p2;
wire   [14:0] trunc_ln44_107_fu_1317_p4;
wire   [14:0] select_ln51_45_fu_2503_p3;
wire   [15:0] trunc_ln44_46_fu_1327_p4;
wire   [0:0] icmp_ln51_46_fu_2515_p2;
wire   [14:0] trunc_ln44_108_fu_1337_p4;
wire   [14:0] select_ln51_46_fu_2521_p3;
wire   [15:0] trunc_ln44_47_fu_1347_p4;
wire   [0:0] icmp_ln51_47_fu_2533_p2;
wire   [14:0] trunc_ln44_109_fu_1357_p4;
wire   [14:0] select_ln51_47_fu_2539_p3;
wire   [15:0] trunc_ln44_48_fu_1367_p4;
wire   [0:0] icmp_ln51_48_fu_2551_p2;
wire   [14:0] trunc_ln44_110_fu_1377_p4;
wire   [14:0] select_ln51_48_fu_2557_p3;
wire   [15:0] trunc_ln44_49_fu_1387_p4;
wire   [0:0] icmp_ln51_49_fu_2569_p2;
wire   [14:0] trunc_ln44_111_fu_1397_p4;
wire   [14:0] select_ln51_49_fu_2575_p3;
wire   [15:0] trunc_ln44_50_fu_1407_p4;
wire   [0:0] icmp_ln51_50_fu_2587_p2;
wire   [14:0] trunc_ln44_112_fu_1417_p4;
wire   [14:0] select_ln51_50_fu_2593_p3;
wire   [15:0] trunc_ln44_51_fu_1427_p4;
wire   [0:0] icmp_ln51_51_fu_2605_p2;
wire   [14:0] trunc_ln44_113_fu_1437_p4;
wire   [14:0] select_ln51_51_fu_2611_p3;
wire   [15:0] trunc_ln44_52_fu_1447_p4;
wire   [0:0] icmp_ln51_52_fu_2623_p2;
wire   [14:0] trunc_ln44_114_fu_1457_p4;
wire   [14:0] select_ln51_52_fu_2629_p3;
wire   [15:0] trunc_ln44_53_fu_1467_p4;
wire   [0:0] icmp_ln51_53_fu_2641_p2;
wire   [14:0] trunc_ln44_115_fu_1477_p4;
wire   [14:0] select_ln51_53_fu_2647_p3;
wire   [15:0] trunc_ln44_54_fu_1487_p4;
wire   [0:0] icmp_ln51_54_fu_2659_p2;
wire   [14:0] trunc_ln44_116_fu_1497_p4;
wire   [14:0] select_ln51_54_fu_2665_p3;
wire   [15:0] trunc_ln44_55_fu_1507_p4;
wire   [0:0] icmp_ln51_55_fu_2677_p2;
wire   [14:0] trunc_ln44_117_fu_1517_p4;
wire   [14:0] select_ln51_55_fu_2683_p3;
wire   [15:0] trunc_ln44_56_fu_1527_p4;
wire   [0:0] icmp_ln51_56_fu_2695_p2;
wire   [14:0] trunc_ln44_118_fu_1537_p4;
wire   [14:0] select_ln51_56_fu_2701_p3;
wire   [15:0] trunc_ln44_57_fu_1547_p4;
wire   [0:0] icmp_ln51_57_fu_2713_p2;
wire   [14:0] trunc_ln44_119_fu_1557_p4;
wire   [14:0] select_ln51_57_fu_2719_p3;
wire   [15:0] trunc_ln44_58_fu_1567_p4;
wire   [0:0] icmp_ln51_58_fu_2731_p2;
wire   [14:0] trunc_ln44_120_fu_1577_p4;
wire   [14:0] select_ln51_58_fu_2737_p3;
wire   [15:0] trunc_ln44_59_fu_1587_p4;
wire   [0:0] icmp_ln51_59_fu_2749_p2;
wire   [14:0] trunc_ln44_121_fu_1597_p4;
wire   [14:0] select_ln51_59_fu_2755_p3;
wire   [15:0] trunc_ln44_60_fu_1607_p4;
wire   [0:0] icmp_ln51_60_fu_2767_p2;
wire   [14:0] trunc_ln44_122_fu_1617_p4;
wire   [14:0] select_ln51_60_fu_2773_p3;
wire   [15:0] trunc_ln44_61_fu_1627_p4;
wire   [0:0] icmp_ln51_61_fu_2785_p2;
wire   [14:0] trunc_ln44_123_fu_1637_p4;
wire   [14:0] select_ln51_61_fu_2791_p3;
wire   [15:0] trunc_ln44_62_fu_1647_p4;
wire   [0:0] icmp_ln51_62_fu_2803_p2;
wire   [14:0] trunc_ln44_124_fu_1657_p4;
wire   [14:0] select_ln51_62_fu_2809_p3;
wire   [15:0] trunc_ln44_63_fu_1667_p4;
wire   [0:0] icmp_ln51_63_fu_2821_p2;
wire   [14:0] trunc_ln4_fu_1677_p4;
wire   [14:0] select_ln51_63_fu_2827_p3;
wire   [15:0] zext_ln51_63_fu_2817_p1;
wire   [15:0] zext_ln51_62_fu_2799_p1;
wire   [15:0] zext_ln51_61_fu_2781_p1;
wire   [15:0] zext_ln51_60_fu_2763_p1;
wire   [15:0] zext_ln51_59_fu_2745_p1;
wire   [15:0] zext_ln51_58_fu_2727_p1;
wire   [15:0] zext_ln51_57_fu_2709_p1;
wire   [15:0] zext_ln51_56_fu_2691_p1;
wire   [15:0] zext_ln51_55_fu_2673_p1;
wire   [15:0] zext_ln51_54_fu_2655_p1;
wire   [15:0] zext_ln51_53_fu_2637_p1;
wire   [15:0] zext_ln51_52_fu_2619_p1;
wire   [15:0] zext_ln51_51_fu_2601_p1;
wire   [15:0] zext_ln51_50_fu_2583_p1;
wire   [15:0] zext_ln51_49_fu_2565_p1;
wire   [15:0] zext_ln51_48_fu_2547_p1;
wire   [15:0] zext_ln51_47_fu_2529_p1;
wire   [15:0] zext_ln51_46_fu_2511_p1;
wire   [15:0] zext_ln51_45_fu_2493_p1;
wire   [15:0] zext_ln51_44_fu_2475_p1;
wire   [15:0] zext_ln51_43_fu_2457_p1;
wire   [15:0] zext_ln51_42_fu_2439_p1;
wire   [15:0] zext_ln51_41_fu_2421_p1;
wire   [15:0] zext_ln51_40_fu_2403_p1;
wire   [15:0] zext_ln51_39_fu_2385_p1;
wire   [15:0] zext_ln51_38_fu_2367_p1;
wire   [15:0] zext_ln51_37_fu_2349_p1;
wire   [15:0] zext_ln51_36_fu_2331_p1;
wire   [15:0] zext_ln51_35_fu_2313_p1;
wire   [15:0] zext_ln51_34_fu_2295_p1;
wire   [15:0] zext_ln51_33_fu_2277_p1;
wire   [15:0] zext_ln51_32_fu_2259_p1;
wire   [15:0] zext_ln51_31_fu_2241_p1;
wire   [15:0] zext_ln51_30_fu_2223_p1;
wire   [15:0] zext_ln51_29_fu_2205_p1;
wire   [15:0] zext_ln51_28_fu_2187_p1;
wire   [15:0] zext_ln51_27_fu_2169_p1;
wire   [15:0] zext_ln51_26_fu_2151_p1;
wire   [15:0] zext_ln51_25_fu_2133_p1;
wire   [15:0] zext_ln51_24_fu_2115_p1;
wire   [15:0] zext_ln51_23_fu_2097_p1;
wire   [15:0] zext_ln51_22_fu_2079_p1;
wire   [15:0] zext_ln51_21_fu_2061_p1;
wire   [15:0] zext_ln51_20_fu_2043_p1;
wire   [15:0] zext_ln51_19_fu_2025_p1;
wire   [15:0] zext_ln51_18_fu_2007_p1;
wire   [15:0] zext_ln51_17_fu_1989_p1;
wire   [15:0] zext_ln51_16_fu_1971_p1;
wire   [15:0] zext_ln51_15_fu_1953_p1;
wire   [15:0] zext_ln51_14_fu_1935_p1;
wire   [15:0] zext_ln51_13_fu_1917_p1;
wire   [15:0] zext_ln51_12_fu_1899_p1;
wire   [15:0] zext_ln51_11_fu_1881_p1;
wire   [15:0] zext_ln51_10_fu_1863_p1;
wire   [15:0] zext_ln51_9_fu_1845_p1;
wire   [15:0] zext_ln51_8_fu_1827_p1;
wire   [15:0] zext_ln51_7_fu_1809_p1;
wire   [15:0] zext_ln51_6_fu_1791_p1;
wire   [15:0] zext_ln51_5_fu_1773_p1;
wire   [15:0] zext_ln51_4_fu_1755_p1;
wire   [15:0] zext_ln51_3_fu_1737_p1;
wire   [15:0] zext_ln51_2_fu_1719_p1;
wire   [15:0] zext_ln51_fu_1701_p1;
wire   [1022:0] or_ln57_s_fu_2835_p65;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_blk_n = layer2_out_empty_n;
    end else begin
        layer2_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_read = 1'b1;
    end else begin
        layer2_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer3_out_blk_n = layer3_out_full_n;
    end else begin
        layer3_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        layer3_out_write = 1'b1;
    end else begin
        layer3_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (layer3_out_full_n == 1'b0) | (layer2_out_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign icmp_ln51_10_fu_1867_p2 = (($signed(trunc_ln44_10_fu_607_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_11_fu_1885_p2 = (($signed(trunc_ln44_11_fu_627_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_12_fu_1903_p2 = (($signed(trunc_ln44_12_fu_647_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_13_fu_1921_p2 = (($signed(trunc_ln44_13_fu_667_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_14_fu_1939_p2 = (($signed(trunc_ln44_14_fu_687_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_15_fu_1957_p2 = (($signed(trunc_ln44_15_fu_707_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_16_fu_1975_p2 = (($signed(trunc_ln44_16_fu_727_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_17_fu_1993_p2 = (($signed(trunc_ln44_17_fu_747_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_18_fu_2011_p2 = (($signed(trunc_ln44_18_fu_767_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_19_fu_2029_p2 = (($signed(trunc_ln44_19_fu_787_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_1_fu_1705_p2 = (($signed(trunc_ln44_1_fu_427_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_20_fu_2047_p2 = (($signed(trunc_ln44_20_fu_807_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_21_fu_2065_p2 = (($signed(trunc_ln44_21_fu_827_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_22_fu_2083_p2 = (($signed(trunc_ln44_22_fu_847_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_23_fu_2101_p2 = (($signed(trunc_ln44_23_fu_867_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_24_fu_2119_p2 = (($signed(trunc_ln44_24_fu_887_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_25_fu_2137_p2 = (($signed(trunc_ln44_25_fu_907_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_26_fu_2155_p2 = (($signed(trunc_ln44_26_fu_927_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_27_fu_2173_p2 = (($signed(trunc_ln44_27_fu_947_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_28_fu_2191_p2 = (($signed(trunc_ln44_28_fu_967_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_29_fu_2209_p2 = (($signed(trunc_ln44_29_fu_987_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_2_fu_1723_p2 = (($signed(trunc_ln44_2_fu_447_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_30_fu_2227_p2 = (($signed(trunc_ln44_30_fu_1007_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_31_fu_2245_p2 = (($signed(trunc_ln44_31_fu_1027_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_32_fu_2263_p2 = (($signed(trunc_ln44_32_fu_1047_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_33_fu_2281_p2 = (($signed(trunc_ln44_33_fu_1067_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_34_fu_2299_p2 = (($signed(trunc_ln44_34_fu_1087_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_35_fu_2317_p2 = (($signed(trunc_ln44_35_fu_1107_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_36_fu_2335_p2 = (($signed(trunc_ln44_36_fu_1127_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_37_fu_2353_p2 = (($signed(trunc_ln44_37_fu_1147_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_38_fu_2371_p2 = (($signed(trunc_ln44_38_fu_1167_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_39_fu_2389_p2 = (($signed(trunc_ln44_39_fu_1187_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_3_fu_1741_p2 = (($signed(trunc_ln44_3_fu_467_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_40_fu_2407_p2 = (($signed(trunc_ln44_40_fu_1207_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_41_fu_2425_p2 = (($signed(trunc_ln44_41_fu_1227_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_42_fu_2443_p2 = (($signed(trunc_ln44_42_fu_1247_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_43_fu_2461_p2 = (($signed(trunc_ln44_43_fu_1267_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_44_fu_2479_p2 = (($signed(trunc_ln44_44_fu_1287_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_45_fu_2497_p2 = (($signed(trunc_ln44_45_fu_1307_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_46_fu_2515_p2 = (($signed(trunc_ln44_46_fu_1327_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_47_fu_2533_p2 = (($signed(trunc_ln44_47_fu_1347_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_48_fu_2551_p2 = (($signed(trunc_ln44_48_fu_1367_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_49_fu_2569_p2 = (($signed(trunc_ln44_49_fu_1387_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_4_fu_1759_p2 = (($signed(trunc_ln44_4_fu_487_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_50_fu_2587_p2 = (($signed(trunc_ln44_50_fu_1407_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_51_fu_2605_p2 = (($signed(trunc_ln44_51_fu_1427_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_52_fu_2623_p2 = (($signed(trunc_ln44_52_fu_1447_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_53_fu_2641_p2 = (($signed(trunc_ln44_53_fu_1467_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_54_fu_2659_p2 = (($signed(trunc_ln44_54_fu_1487_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_55_fu_2677_p2 = (($signed(trunc_ln44_55_fu_1507_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_56_fu_2695_p2 = (($signed(trunc_ln44_56_fu_1527_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_57_fu_2713_p2 = (($signed(trunc_ln44_57_fu_1547_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_58_fu_2731_p2 = (($signed(trunc_ln44_58_fu_1567_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_59_fu_2749_p2 = (($signed(trunc_ln44_59_fu_1587_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_5_fu_1777_p2 = (($signed(trunc_ln44_5_fu_507_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_60_fu_2767_p2 = (($signed(trunc_ln44_60_fu_1607_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_61_fu_2785_p2 = (($signed(trunc_ln44_61_fu_1627_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_62_fu_2803_p2 = (($signed(trunc_ln44_62_fu_1647_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_63_fu_2821_p2 = (($signed(trunc_ln44_63_fu_1667_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_6_fu_1795_p2 = (($signed(trunc_ln44_6_fu_527_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_7_fu_1813_p2 = (($signed(trunc_ln44_7_fu_547_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_8_fu_1831_p2 = (($signed(trunc_ln44_8_fu_567_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_9_fu_1849_p2 = (($signed(trunc_ln44_9_fu_587_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_1687_p2 = (($signed(trunc_ln44_fu_419_p1) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign layer3_out_din = or_ln57_s_fu_2835_p65;

assign or_ln57_s_fu_2835_p65 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{select_ln51_63_fu_2827_p3}, {zext_ln51_63_fu_2817_p1}}, {zext_ln51_62_fu_2799_p1}}, {zext_ln51_61_fu_2781_p1}}, {zext_ln51_60_fu_2763_p1}}, {zext_ln51_59_fu_2745_p1}}, {zext_ln51_58_fu_2727_p1}}, {zext_ln51_57_fu_2709_p1}}, {zext_ln51_56_fu_2691_p1}}, {zext_ln51_55_fu_2673_p1}}, {zext_ln51_54_fu_2655_p1}}, {zext_ln51_53_fu_2637_p1}}, {zext_ln51_52_fu_2619_p1}}, {zext_ln51_51_fu_2601_p1}}, {zext_ln51_50_fu_2583_p1}}, {zext_ln51_49_fu_2565_p1}}, {zext_ln51_48_fu_2547_p1}}, {zext_ln51_47_fu_2529_p1}}, {zext_ln51_46_fu_2511_p1}}, {zext_ln51_45_fu_2493_p1}}, {zext_ln51_44_fu_2475_p1}}, {zext_ln51_43_fu_2457_p1}}, {zext_ln51_42_fu_2439_p1}}, {zext_ln51_41_fu_2421_p1}}, {zext_ln51_40_fu_2403_p1}}, {zext_ln51_39_fu_2385_p1}}, {zext_ln51_38_fu_2367_p1}}, {zext_ln51_37_fu_2349_p1}}, {zext_ln51_36_fu_2331_p1}}, {zext_ln51_35_fu_2313_p1}}, {zext_ln51_34_fu_2295_p1}}, {zext_ln51_33_fu_2277_p1}}, {zext_ln51_32_fu_2259_p1}}, {zext_ln51_31_fu_2241_p1}}, {zext_ln51_30_fu_2223_p1}}, 
    {zext_ln51_29_fu_2205_p1}}, {zext_ln51_28_fu_2187_p1}}, {zext_ln51_27_fu_2169_p1}}, {zext_ln51_26_fu_2151_p1}}, {zext_ln51_25_fu_2133_p1}}, {zext_ln51_24_fu_2115_p1}}, {zext_ln51_23_fu_2097_p1}}, {zext_ln51_22_fu_2079_p1}}, {zext_ln51_21_fu_2061_p1}}, {zext_ln51_20_fu_2043_p1}}, {zext_ln51_19_fu_2025_p1}}, {zext_ln51_18_fu_2007_p1}}, {zext_ln51_17_fu_1989_p1}}, {zext_ln51_16_fu_1971_p1}}, {zext_ln51_15_fu_1953_p1}}, {zext_ln51_14_fu_1935_p1}}, {zext_ln51_13_fu_1917_p1}}, {zext_ln51_12_fu_1899_p1}}, {zext_ln51_11_fu_1881_p1}}, {zext_ln51_10_fu_1863_p1}}, {zext_ln51_9_fu_1845_p1}}, {zext_ln51_8_fu_1827_p1}}, {zext_ln51_7_fu_1809_p1}}, {zext_ln51_6_fu_1791_p1}}, {zext_ln51_5_fu_1773_p1}}, {zext_ln51_4_fu_1755_p1}}, {zext_ln51_3_fu_1737_p1}}, {zext_ln51_2_fu_1719_p1}}, {zext_ln51_fu_1701_p1}};

assign select_ln51_10_fu_1873_p3 = ((icmp_ln51_10_fu_1867_p2[0:0] == 1'b1) ? trunc_ln44_72_fu_617_p4 : 15'd0);

assign select_ln51_11_fu_1891_p3 = ((icmp_ln51_11_fu_1885_p2[0:0] == 1'b1) ? trunc_ln44_73_fu_637_p4 : 15'd0);

assign select_ln51_12_fu_1909_p3 = ((icmp_ln51_12_fu_1903_p2[0:0] == 1'b1) ? trunc_ln44_74_fu_657_p4 : 15'd0);

assign select_ln51_13_fu_1927_p3 = ((icmp_ln51_13_fu_1921_p2[0:0] == 1'b1) ? trunc_ln44_75_fu_677_p4 : 15'd0);

assign select_ln51_14_fu_1945_p3 = ((icmp_ln51_14_fu_1939_p2[0:0] == 1'b1) ? trunc_ln44_76_fu_697_p4 : 15'd0);

assign select_ln51_15_fu_1963_p3 = ((icmp_ln51_15_fu_1957_p2[0:0] == 1'b1) ? trunc_ln44_77_fu_717_p4 : 15'd0);

assign select_ln51_16_fu_1981_p3 = ((icmp_ln51_16_fu_1975_p2[0:0] == 1'b1) ? trunc_ln44_78_fu_737_p4 : 15'd0);

assign select_ln51_17_fu_1999_p3 = ((icmp_ln51_17_fu_1993_p2[0:0] == 1'b1) ? trunc_ln44_79_fu_757_p4 : 15'd0);

assign select_ln51_18_fu_2017_p3 = ((icmp_ln51_18_fu_2011_p2[0:0] == 1'b1) ? trunc_ln44_80_fu_777_p4 : 15'd0);

assign select_ln51_19_fu_2035_p3 = ((icmp_ln51_19_fu_2029_p2[0:0] == 1'b1) ? trunc_ln44_81_fu_797_p4 : 15'd0);

assign select_ln51_1_fu_1711_p3 = ((icmp_ln51_1_fu_1705_p2[0:0] == 1'b1) ? trunc_ln44_s_fu_437_p4 : 15'd0);

assign select_ln51_20_fu_2053_p3 = ((icmp_ln51_20_fu_2047_p2[0:0] == 1'b1) ? trunc_ln44_82_fu_817_p4 : 15'd0);

assign select_ln51_21_fu_2071_p3 = ((icmp_ln51_21_fu_2065_p2[0:0] == 1'b1) ? trunc_ln44_83_fu_837_p4 : 15'd0);

assign select_ln51_22_fu_2089_p3 = ((icmp_ln51_22_fu_2083_p2[0:0] == 1'b1) ? trunc_ln44_84_fu_857_p4 : 15'd0);

assign select_ln51_23_fu_2107_p3 = ((icmp_ln51_23_fu_2101_p2[0:0] == 1'b1) ? trunc_ln44_85_fu_877_p4 : 15'd0);

assign select_ln51_24_fu_2125_p3 = ((icmp_ln51_24_fu_2119_p2[0:0] == 1'b1) ? trunc_ln44_86_fu_897_p4 : 15'd0);

assign select_ln51_25_fu_2143_p3 = ((icmp_ln51_25_fu_2137_p2[0:0] == 1'b1) ? trunc_ln44_87_fu_917_p4 : 15'd0);

assign select_ln51_26_fu_2161_p3 = ((icmp_ln51_26_fu_2155_p2[0:0] == 1'b1) ? trunc_ln44_88_fu_937_p4 : 15'd0);

assign select_ln51_27_fu_2179_p3 = ((icmp_ln51_27_fu_2173_p2[0:0] == 1'b1) ? trunc_ln44_89_fu_957_p4 : 15'd0);

assign select_ln51_28_fu_2197_p3 = ((icmp_ln51_28_fu_2191_p2[0:0] == 1'b1) ? trunc_ln44_90_fu_977_p4 : 15'd0);

assign select_ln51_29_fu_2215_p3 = ((icmp_ln51_29_fu_2209_p2[0:0] == 1'b1) ? trunc_ln44_91_fu_997_p4 : 15'd0);

assign select_ln51_2_fu_1729_p3 = ((icmp_ln51_2_fu_1723_p2[0:0] == 1'b1) ? trunc_ln44_64_fu_457_p4 : 15'd0);

assign select_ln51_30_fu_2233_p3 = ((icmp_ln51_30_fu_2227_p2[0:0] == 1'b1) ? trunc_ln44_92_fu_1017_p4 : 15'd0);

assign select_ln51_31_fu_2251_p3 = ((icmp_ln51_31_fu_2245_p2[0:0] == 1'b1) ? trunc_ln44_93_fu_1037_p4 : 15'd0);

assign select_ln51_32_fu_2269_p3 = ((icmp_ln51_32_fu_2263_p2[0:0] == 1'b1) ? trunc_ln44_94_fu_1057_p4 : 15'd0);

assign select_ln51_33_fu_2287_p3 = ((icmp_ln51_33_fu_2281_p2[0:0] == 1'b1) ? trunc_ln44_95_fu_1077_p4 : 15'd0);

assign select_ln51_34_fu_2305_p3 = ((icmp_ln51_34_fu_2299_p2[0:0] == 1'b1) ? trunc_ln44_96_fu_1097_p4 : 15'd0);

assign select_ln51_35_fu_2323_p3 = ((icmp_ln51_35_fu_2317_p2[0:0] == 1'b1) ? trunc_ln44_97_fu_1117_p4 : 15'd0);

assign select_ln51_36_fu_2341_p3 = ((icmp_ln51_36_fu_2335_p2[0:0] == 1'b1) ? trunc_ln44_98_fu_1137_p4 : 15'd0);

assign select_ln51_37_fu_2359_p3 = ((icmp_ln51_37_fu_2353_p2[0:0] == 1'b1) ? trunc_ln44_99_fu_1157_p4 : 15'd0);

assign select_ln51_38_fu_2377_p3 = ((icmp_ln51_38_fu_2371_p2[0:0] == 1'b1) ? trunc_ln44_100_fu_1177_p4 : 15'd0);

assign select_ln51_39_fu_2395_p3 = ((icmp_ln51_39_fu_2389_p2[0:0] == 1'b1) ? trunc_ln44_101_fu_1197_p4 : 15'd0);

assign select_ln51_3_fu_1747_p3 = ((icmp_ln51_3_fu_1741_p2[0:0] == 1'b1) ? trunc_ln44_65_fu_477_p4 : 15'd0);

assign select_ln51_40_fu_2413_p3 = ((icmp_ln51_40_fu_2407_p2[0:0] == 1'b1) ? trunc_ln44_102_fu_1217_p4 : 15'd0);

assign select_ln51_41_fu_2431_p3 = ((icmp_ln51_41_fu_2425_p2[0:0] == 1'b1) ? trunc_ln44_103_fu_1237_p4 : 15'd0);

assign select_ln51_42_fu_2449_p3 = ((icmp_ln51_42_fu_2443_p2[0:0] == 1'b1) ? trunc_ln44_104_fu_1257_p4 : 15'd0);

assign select_ln51_43_fu_2467_p3 = ((icmp_ln51_43_fu_2461_p2[0:0] == 1'b1) ? trunc_ln44_105_fu_1277_p4 : 15'd0);

assign select_ln51_44_fu_2485_p3 = ((icmp_ln51_44_fu_2479_p2[0:0] == 1'b1) ? trunc_ln44_106_fu_1297_p4 : 15'd0);

assign select_ln51_45_fu_2503_p3 = ((icmp_ln51_45_fu_2497_p2[0:0] == 1'b1) ? trunc_ln44_107_fu_1317_p4 : 15'd0);

assign select_ln51_46_fu_2521_p3 = ((icmp_ln51_46_fu_2515_p2[0:0] == 1'b1) ? trunc_ln44_108_fu_1337_p4 : 15'd0);

assign select_ln51_47_fu_2539_p3 = ((icmp_ln51_47_fu_2533_p2[0:0] == 1'b1) ? trunc_ln44_109_fu_1357_p4 : 15'd0);

assign select_ln51_48_fu_2557_p3 = ((icmp_ln51_48_fu_2551_p2[0:0] == 1'b1) ? trunc_ln44_110_fu_1377_p4 : 15'd0);

assign select_ln51_49_fu_2575_p3 = ((icmp_ln51_49_fu_2569_p2[0:0] == 1'b1) ? trunc_ln44_111_fu_1397_p4 : 15'd0);

assign select_ln51_4_fu_1765_p3 = ((icmp_ln51_4_fu_1759_p2[0:0] == 1'b1) ? trunc_ln44_66_fu_497_p4 : 15'd0);

assign select_ln51_50_fu_2593_p3 = ((icmp_ln51_50_fu_2587_p2[0:0] == 1'b1) ? trunc_ln44_112_fu_1417_p4 : 15'd0);

assign select_ln51_51_fu_2611_p3 = ((icmp_ln51_51_fu_2605_p2[0:0] == 1'b1) ? trunc_ln44_113_fu_1437_p4 : 15'd0);

assign select_ln51_52_fu_2629_p3 = ((icmp_ln51_52_fu_2623_p2[0:0] == 1'b1) ? trunc_ln44_114_fu_1457_p4 : 15'd0);

assign select_ln51_53_fu_2647_p3 = ((icmp_ln51_53_fu_2641_p2[0:0] == 1'b1) ? trunc_ln44_115_fu_1477_p4 : 15'd0);

assign select_ln51_54_fu_2665_p3 = ((icmp_ln51_54_fu_2659_p2[0:0] == 1'b1) ? trunc_ln44_116_fu_1497_p4 : 15'd0);

assign select_ln51_55_fu_2683_p3 = ((icmp_ln51_55_fu_2677_p2[0:0] == 1'b1) ? trunc_ln44_117_fu_1517_p4 : 15'd0);

assign select_ln51_56_fu_2701_p3 = ((icmp_ln51_56_fu_2695_p2[0:0] == 1'b1) ? trunc_ln44_118_fu_1537_p4 : 15'd0);

assign select_ln51_57_fu_2719_p3 = ((icmp_ln51_57_fu_2713_p2[0:0] == 1'b1) ? trunc_ln44_119_fu_1557_p4 : 15'd0);

assign select_ln51_58_fu_2737_p3 = ((icmp_ln51_58_fu_2731_p2[0:0] == 1'b1) ? trunc_ln44_120_fu_1577_p4 : 15'd0);

assign select_ln51_59_fu_2755_p3 = ((icmp_ln51_59_fu_2749_p2[0:0] == 1'b1) ? trunc_ln44_121_fu_1597_p4 : 15'd0);

assign select_ln51_5_fu_1783_p3 = ((icmp_ln51_5_fu_1777_p2[0:0] == 1'b1) ? trunc_ln44_67_fu_517_p4 : 15'd0);

assign select_ln51_60_fu_2773_p3 = ((icmp_ln51_60_fu_2767_p2[0:0] == 1'b1) ? trunc_ln44_122_fu_1617_p4 : 15'd0);

assign select_ln51_61_fu_2791_p3 = ((icmp_ln51_61_fu_2785_p2[0:0] == 1'b1) ? trunc_ln44_123_fu_1637_p4 : 15'd0);

assign select_ln51_62_fu_2809_p3 = ((icmp_ln51_62_fu_2803_p2[0:0] == 1'b1) ? trunc_ln44_124_fu_1657_p4 : 15'd0);

assign select_ln51_63_fu_2827_p3 = ((icmp_ln51_63_fu_2821_p2[0:0] == 1'b1) ? trunc_ln4_fu_1677_p4 : 15'd0);

assign select_ln51_6_fu_1801_p3 = ((icmp_ln51_6_fu_1795_p2[0:0] == 1'b1) ? trunc_ln44_68_fu_537_p4 : 15'd0);

assign select_ln51_7_fu_1819_p3 = ((icmp_ln51_7_fu_1813_p2[0:0] == 1'b1) ? trunc_ln44_69_fu_557_p4 : 15'd0);

assign select_ln51_8_fu_1837_p3 = ((icmp_ln51_8_fu_1831_p2[0:0] == 1'b1) ? trunc_ln44_70_fu_577_p4 : 15'd0);

assign select_ln51_9_fu_1855_p3 = ((icmp_ln51_9_fu_1849_p2[0:0] == 1'b1) ? trunc_ln44_71_fu_597_p4 : 15'd0);

assign select_ln51_fu_1693_p3 = ((icmp_ln51_fu_1687_p2[0:0] == 1'b1) ? trunc_ln44_126_fu_423_p1 : 15'd0);

assign start_out = real_start;

assign trunc_ln44_100_fu_1177_p4 = {{layer2_out_dout[622:608]}};

assign trunc_ln44_101_fu_1197_p4 = {{layer2_out_dout[638:624]}};

assign trunc_ln44_102_fu_1217_p4 = {{layer2_out_dout[654:640]}};

assign trunc_ln44_103_fu_1237_p4 = {{layer2_out_dout[670:656]}};

assign trunc_ln44_104_fu_1257_p4 = {{layer2_out_dout[686:672]}};

assign trunc_ln44_105_fu_1277_p4 = {{layer2_out_dout[702:688]}};

assign trunc_ln44_106_fu_1297_p4 = {{layer2_out_dout[718:704]}};

assign trunc_ln44_107_fu_1317_p4 = {{layer2_out_dout[734:720]}};

assign trunc_ln44_108_fu_1337_p4 = {{layer2_out_dout[750:736]}};

assign trunc_ln44_109_fu_1357_p4 = {{layer2_out_dout[766:752]}};

assign trunc_ln44_10_fu_607_p4 = {{layer2_out_dout[175:160]}};

assign trunc_ln44_110_fu_1377_p4 = {{layer2_out_dout[782:768]}};

assign trunc_ln44_111_fu_1397_p4 = {{layer2_out_dout[798:784]}};

assign trunc_ln44_112_fu_1417_p4 = {{layer2_out_dout[814:800]}};

assign trunc_ln44_113_fu_1437_p4 = {{layer2_out_dout[830:816]}};

assign trunc_ln44_114_fu_1457_p4 = {{layer2_out_dout[846:832]}};

assign trunc_ln44_115_fu_1477_p4 = {{layer2_out_dout[862:848]}};

assign trunc_ln44_116_fu_1497_p4 = {{layer2_out_dout[878:864]}};

assign trunc_ln44_117_fu_1517_p4 = {{layer2_out_dout[894:880]}};

assign trunc_ln44_118_fu_1537_p4 = {{layer2_out_dout[910:896]}};

assign trunc_ln44_119_fu_1557_p4 = {{layer2_out_dout[926:912]}};

assign trunc_ln44_11_fu_627_p4 = {{layer2_out_dout[191:176]}};

assign trunc_ln44_120_fu_1577_p4 = {{layer2_out_dout[942:928]}};

assign trunc_ln44_121_fu_1597_p4 = {{layer2_out_dout[958:944]}};

assign trunc_ln44_122_fu_1617_p4 = {{layer2_out_dout[974:960]}};

assign trunc_ln44_123_fu_1637_p4 = {{layer2_out_dout[990:976]}};

assign trunc_ln44_124_fu_1657_p4 = {{layer2_out_dout[1006:992]}};

assign trunc_ln44_126_fu_423_p1 = layer2_out_dout[14:0];

assign trunc_ln44_12_fu_647_p4 = {{layer2_out_dout[207:192]}};

assign trunc_ln44_13_fu_667_p4 = {{layer2_out_dout[223:208]}};

assign trunc_ln44_14_fu_687_p4 = {{layer2_out_dout[239:224]}};

assign trunc_ln44_15_fu_707_p4 = {{layer2_out_dout[255:240]}};

assign trunc_ln44_16_fu_727_p4 = {{layer2_out_dout[271:256]}};

assign trunc_ln44_17_fu_747_p4 = {{layer2_out_dout[287:272]}};

assign trunc_ln44_18_fu_767_p4 = {{layer2_out_dout[303:288]}};

assign trunc_ln44_19_fu_787_p4 = {{layer2_out_dout[319:304]}};

assign trunc_ln44_1_fu_427_p4 = {{layer2_out_dout[31:16]}};

assign trunc_ln44_20_fu_807_p4 = {{layer2_out_dout[335:320]}};

assign trunc_ln44_21_fu_827_p4 = {{layer2_out_dout[351:336]}};

assign trunc_ln44_22_fu_847_p4 = {{layer2_out_dout[367:352]}};

assign trunc_ln44_23_fu_867_p4 = {{layer2_out_dout[383:368]}};

assign trunc_ln44_24_fu_887_p4 = {{layer2_out_dout[399:384]}};

assign trunc_ln44_25_fu_907_p4 = {{layer2_out_dout[415:400]}};

assign trunc_ln44_26_fu_927_p4 = {{layer2_out_dout[431:416]}};

assign trunc_ln44_27_fu_947_p4 = {{layer2_out_dout[447:432]}};

assign trunc_ln44_28_fu_967_p4 = {{layer2_out_dout[463:448]}};

assign trunc_ln44_29_fu_987_p4 = {{layer2_out_dout[479:464]}};

assign trunc_ln44_2_fu_447_p4 = {{layer2_out_dout[47:32]}};

assign trunc_ln44_30_fu_1007_p4 = {{layer2_out_dout[495:480]}};

assign trunc_ln44_31_fu_1027_p4 = {{layer2_out_dout[511:496]}};

assign trunc_ln44_32_fu_1047_p4 = {{layer2_out_dout[527:512]}};

assign trunc_ln44_33_fu_1067_p4 = {{layer2_out_dout[543:528]}};

assign trunc_ln44_34_fu_1087_p4 = {{layer2_out_dout[559:544]}};

assign trunc_ln44_35_fu_1107_p4 = {{layer2_out_dout[575:560]}};

assign trunc_ln44_36_fu_1127_p4 = {{layer2_out_dout[591:576]}};

assign trunc_ln44_37_fu_1147_p4 = {{layer2_out_dout[607:592]}};

assign trunc_ln44_38_fu_1167_p4 = {{layer2_out_dout[623:608]}};

assign trunc_ln44_39_fu_1187_p4 = {{layer2_out_dout[639:624]}};

assign trunc_ln44_3_fu_467_p4 = {{layer2_out_dout[63:48]}};

assign trunc_ln44_40_fu_1207_p4 = {{layer2_out_dout[655:640]}};

assign trunc_ln44_41_fu_1227_p4 = {{layer2_out_dout[671:656]}};

assign trunc_ln44_42_fu_1247_p4 = {{layer2_out_dout[687:672]}};

assign trunc_ln44_43_fu_1267_p4 = {{layer2_out_dout[703:688]}};

assign trunc_ln44_44_fu_1287_p4 = {{layer2_out_dout[719:704]}};

assign trunc_ln44_45_fu_1307_p4 = {{layer2_out_dout[735:720]}};

assign trunc_ln44_46_fu_1327_p4 = {{layer2_out_dout[751:736]}};

assign trunc_ln44_47_fu_1347_p4 = {{layer2_out_dout[767:752]}};

assign trunc_ln44_48_fu_1367_p4 = {{layer2_out_dout[783:768]}};

assign trunc_ln44_49_fu_1387_p4 = {{layer2_out_dout[799:784]}};

assign trunc_ln44_4_fu_487_p4 = {{layer2_out_dout[79:64]}};

assign trunc_ln44_50_fu_1407_p4 = {{layer2_out_dout[815:800]}};

assign trunc_ln44_51_fu_1427_p4 = {{layer2_out_dout[831:816]}};

assign trunc_ln44_52_fu_1447_p4 = {{layer2_out_dout[847:832]}};

assign trunc_ln44_53_fu_1467_p4 = {{layer2_out_dout[863:848]}};

assign trunc_ln44_54_fu_1487_p4 = {{layer2_out_dout[879:864]}};

assign trunc_ln44_55_fu_1507_p4 = {{layer2_out_dout[895:880]}};

assign trunc_ln44_56_fu_1527_p4 = {{layer2_out_dout[911:896]}};

assign trunc_ln44_57_fu_1547_p4 = {{layer2_out_dout[927:912]}};

assign trunc_ln44_58_fu_1567_p4 = {{layer2_out_dout[943:928]}};

assign trunc_ln44_59_fu_1587_p4 = {{layer2_out_dout[959:944]}};

assign trunc_ln44_5_fu_507_p4 = {{layer2_out_dout[95:80]}};

assign trunc_ln44_60_fu_1607_p4 = {{layer2_out_dout[975:960]}};

assign trunc_ln44_61_fu_1627_p4 = {{layer2_out_dout[991:976]}};

assign trunc_ln44_62_fu_1647_p4 = {{layer2_out_dout[1007:992]}};

assign trunc_ln44_63_fu_1667_p4 = {{layer2_out_dout[1023:1008]}};

assign trunc_ln44_64_fu_457_p4 = {{layer2_out_dout[46:32]}};

assign trunc_ln44_65_fu_477_p4 = {{layer2_out_dout[62:48]}};

assign trunc_ln44_66_fu_497_p4 = {{layer2_out_dout[78:64]}};

assign trunc_ln44_67_fu_517_p4 = {{layer2_out_dout[94:80]}};

assign trunc_ln44_68_fu_537_p4 = {{layer2_out_dout[110:96]}};

assign trunc_ln44_69_fu_557_p4 = {{layer2_out_dout[126:112]}};

assign trunc_ln44_6_fu_527_p4 = {{layer2_out_dout[111:96]}};

assign trunc_ln44_70_fu_577_p4 = {{layer2_out_dout[142:128]}};

assign trunc_ln44_71_fu_597_p4 = {{layer2_out_dout[158:144]}};

assign trunc_ln44_72_fu_617_p4 = {{layer2_out_dout[174:160]}};

assign trunc_ln44_73_fu_637_p4 = {{layer2_out_dout[190:176]}};

assign trunc_ln44_74_fu_657_p4 = {{layer2_out_dout[206:192]}};

assign trunc_ln44_75_fu_677_p4 = {{layer2_out_dout[222:208]}};

assign trunc_ln44_76_fu_697_p4 = {{layer2_out_dout[238:224]}};

assign trunc_ln44_77_fu_717_p4 = {{layer2_out_dout[254:240]}};

assign trunc_ln44_78_fu_737_p4 = {{layer2_out_dout[270:256]}};

assign trunc_ln44_79_fu_757_p4 = {{layer2_out_dout[286:272]}};

assign trunc_ln44_7_fu_547_p4 = {{layer2_out_dout[127:112]}};

assign trunc_ln44_80_fu_777_p4 = {{layer2_out_dout[302:288]}};

assign trunc_ln44_81_fu_797_p4 = {{layer2_out_dout[318:304]}};

assign trunc_ln44_82_fu_817_p4 = {{layer2_out_dout[334:320]}};

assign trunc_ln44_83_fu_837_p4 = {{layer2_out_dout[350:336]}};

assign trunc_ln44_84_fu_857_p4 = {{layer2_out_dout[366:352]}};

assign trunc_ln44_85_fu_877_p4 = {{layer2_out_dout[382:368]}};

assign trunc_ln44_86_fu_897_p4 = {{layer2_out_dout[398:384]}};

assign trunc_ln44_87_fu_917_p4 = {{layer2_out_dout[414:400]}};

assign trunc_ln44_88_fu_937_p4 = {{layer2_out_dout[430:416]}};

assign trunc_ln44_89_fu_957_p4 = {{layer2_out_dout[446:432]}};

assign trunc_ln44_8_fu_567_p4 = {{layer2_out_dout[143:128]}};

assign trunc_ln44_90_fu_977_p4 = {{layer2_out_dout[462:448]}};

assign trunc_ln44_91_fu_997_p4 = {{layer2_out_dout[478:464]}};

assign trunc_ln44_92_fu_1017_p4 = {{layer2_out_dout[494:480]}};

assign trunc_ln44_93_fu_1037_p4 = {{layer2_out_dout[510:496]}};

assign trunc_ln44_94_fu_1057_p4 = {{layer2_out_dout[526:512]}};

assign trunc_ln44_95_fu_1077_p4 = {{layer2_out_dout[542:528]}};

assign trunc_ln44_96_fu_1097_p4 = {{layer2_out_dout[558:544]}};

assign trunc_ln44_97_fu_1117_p4 = {{layer2_out_dout[574:560]}};

assign trunc_ln44_98_fu_1137_p4 = {{layer2_out_dout[590:576]}};

assign trunc_ln44_99_fu_1157_p4 = {{layer2_out_dout[606:592]}};

assign trunc_ln44_9_fu_587_p4 = {{layer2_out_dout[159:144]}};

assign trunc_ln44_fu_419_p1 = layer2_out_dout[15:0];

assign trunc_ln44_s_fu_437_p4 = {{layer2_out_dout[30:16]}};

assign trunc_ln4_fu_1677_p4 = {{layer2_out_dout[1022:1008]}};

assign zext_ln51_10_fu_1863_p1 = select_ln51_9_fu_1855_p3;

assign zext_ln51_11_fu_1881_p1 = select_ln51_10_fu_1873_p3;

assign zext_ln51_12_fu_1899_p1 = select_ln51_11_fu_1891_p3;

assign zext_ln51_13_fu_1917_p1 = select_ln51_12_fu_1909_p3;

assign zext_ln51_14_fu_1935_p1 = select_ln51_13_fu_1927_p3;

assign zext_ln51_15_fu_1953_p1 = select_ln51_14_fu_1945_p3;

assign zext_ln51_16_fu_1971_p1 = select_ln51_15_fu_1963_p3;

assign zext_ln51_17_fu_1989_p1 = select_ln51_16_fu_1981_p3;

assign zext_ln51_18_fu_2007_p1 = select_ln51_17_fu_1999_p3;

assign zext_ln51_19_fu_2025_p1 = select_ln51_18_fu_2017_p3;

assign zext_ln51_20_fu_2043_p1 = select_ln51_19_fu_2035_p3;

assign zext_ln51_21_fu_2061_p1 = select_ln51_20_fu_2053_p3;

assign zext_ln51_22_fu_2079_p1 = select_ln51_21_fu_2071_p3;

assign zext_ln51_23_fu_2097_p1 = select_ln51_22_fu_2089_p3;

assign zext_ln51_24_fu_2115_p1 = select_ln51_23_fu_2107_p3;

assign zext_ln51_25_fu_2133_p1 = select_ln51_24_fu_2125_p3;

assign zext_ln51_26_fu_2151_p1 = select_ln51_25_fu_2143_p3;

assign zext_ln51_27_fu_2169_p1 = select_ln51_26_fu_2161_p3;

assign zext_ln51_28_fu_2187_p1 = select_ln51_27_fu_2179_p3;

assign zext_ln51_29_fu_2205_p1 = select_ln51_28_fu_2197_p3;

assign zext_ln51_2_fu_1719_p1 = select_ln51_1_fu_1711_p3;

assign zext_ln51_30_fu_2223_p1 = select_ln51_29_fu_2215_p3;

assign zext_ln51_31_fu_2241_p1 = select_ln51_30_fu_2233_p3;

assign zext_ln51_32_fu_2259_p1 = select_ln51_31_fu_2251_p3;

assign zext_ln51_33_fu_2277_p1 = select_ln51_32_fu_2269_p3;

assign zext_ln51_34_fu_2295_p1 = select_ln51_33_fu_2287_p3;

assign zext_ln51_35_fu_2313_p1 = select_ln51_34_fu_2305_p3;

assign zext_ln51_36_fu_2331_p1 = select_ln51_35_fu_2323_p3;

assign zext_ln51_37_fu_2349_p1 = select_ln51_36_fu_2341_p3;

assign zext_ln51_38_fu_2367_p1 = select_ln51_37_fu_2359_p3;

assign zext_ln51_39_fu_2385_p1 = select_ln51_38_fu_2377_p3;

assign zext_ln51_3_fu_1737_p1 = select_ln51_2_fu_1729_p3;

assign zext_ln51_40_fu_2403_p1 = select_ln51_39_fu_2395_p3;

assign zext_ln51_41_fu_2421_p1 = select_ln51_40_fu_2413_p3;

assign zext_ln51_42_fu_2439_p1 = select_ln51_41_fu_2431_p3;

assign zext_ln51_43_fu_2457_p1 = select_ln51_42_fu_2449_p3;

assign zext_ln51_44_fu_2475_p1 = select_ln51_43_fu_2467_p3;

assign zext_ln51_45_fu_2493_p1 = select_ln51_44_fu_2485_p3;

assign zext_ln51_46_fu_2511_p1 = select_ln51_45_fu_2503_p3;

assign zext_ln51_47_fu_2529_p1 = select_ln51_46_fu_2521_p3;

assign zext_ln51_48_fu_2547_p1 = select_ln51_47_fu_2539_p3;

assign zext_ln51_49_fu_2565_p1 = select_ln51_48_fu_2557_p3;

assign zext_ln51_4_fu_1755_p1 = select_ln51_3_fu_1747_p3;

assign zext_ln51_50_fu_2583_p1 = select_ln51_49_fu_2575_p3;

assign zext_ln51_51_fu_2601_p1 = select_ln51_50_fu_2593_p3;

assign zext_ln51_52_fu_2619_p1 = select_ln51_51_fu_2611_p3;

assign zext_ln51_53_fu_2637_p1 = select_ln51_52_fu_2629_p3;

assign zext_ln51_54_fu_2655_p1 = select_ln51_53_fu_2647_p3;

assign zext_ln51_55_fu_2673_p1 = select_ln51_54_fu_2665_p3;

assign zext_ln51_56_fu_2691_p1 = select_ln51_55_fu_2683_p3;

assign zext_ln51_57_fu_2709_p1 = select_ln51_56_fu_2701_p3;

assign zext_ln51_58_fu_2727_p1 = select_ln51_57_fu_2719_p3;

assign zext_ln51_59_fu_2745_p1 = select_ln51_58_fu_2737_p3;

assign zext_ln51_5_fu_1773_p1 = select_ln51_4_fu_1765_p3;

assign zext_ln51_60_fu_2763_p1 = select_ln51_59_fu_2755_p3;

assign zext_ln51_61_fu_2781_p1 = select_ln51_60_fu_2773_p3;

assign zext_ln51_62_fu_2799_p1 = select_ln51_61_fu_2791_p3;

assign zext_ln51_63_fu_2817_p1 = select_ln51_62_fu_2809_p3;

assign zext_ln51_6_fu_1791_p1 = select_ln51_5_fu_1783_p3;

assign zext_ln51_7_fu_1809_p1 = select_ln51_6_fu_1801_p3;

assign zext_ln51_8_fu_1827_p1 = select_ln51_7_fu_1819_p3;

assign zext_ln51_9_fu_1845_p1 = select_ln51_8_fu_1837_p3;

assign zext_ln51_fu_1701_p1 = select_ln51_fu_1693_p3;

endmodule //myproject_relu_array_ap_fixed_64u_array_ap_fixed_16_6_5_3_0_64u_relu_config3_s
