`timescale 1 ns / 1 ps

module AESL_deadlock_kernel_monitor_top ( 
    input wire kernel_monitor_clock,
    input wire kernel_monitor_reset
);
wire [1:0] axis_block_sigs;
wire [11:0] inst_idle_sigs;
wire [7:0] inst_block_sigs;
wire kernel_block;

assign axis_block_sigs[0] = ~AESL_inst_myproject.dense_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_64u_config2_U0.input_1_TDATA_blk_n;
assign axis_block_sigs[1] = ~AESL_inst_myproject.softmax_array_array_ap_fixed_16_6_5_3_0_5u_softmax_config9_U0.grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_5u_softmax_config9_s_fu_26.layer9_out_TDATA_blk_n;

assign inst_idle_sigs[0] = AESL_inst_myproject.dense_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_64u_config2_U0.ap_idle;
assign inst_block_sigs[0] = (AESL_inst_myproject.dense_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_64u_config2_U0.ap_done & ~AESL_inst_myproject.dense_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_64u_config2_U0.ap_continue) | ~AESL_inst_myproject.dense_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_64u_config2_U0.layer2_out_blk_n;
assign inst_idle_sigs[1] = AESL_inst_myproject.relu_array_ap_fixed_64u_array_ap_fixed_16_6_5_3_0_64u_relu_config3_U0.ap_idle;
assign inst_block_sigs[1] = (AESL_inst_myproject.relu_array_ap_fixed_64u_array_ap_fixed_16_6_5_3_0_64u_relu_config3_U0.ap_done & ~AESL_inst_myproject.relu_array_ap_fixed_64u_array_ap_fixed_16_6_5_3_0_64u_relu_config3_U0.ap_continue) | ~AESL_inst_myproject.relu_array_ap_fixed_64u_array_ap_fixed_16_6_5_3_0_64u_relu_config3_U0.layer2_out_blk_n | ~AESL_inst_myproject.relu_array_ap_fixed_64u_array_ap_fixed_16_6_5_3_0_64u_relu_config3_U0.layer3_out_blk_n;
assign inst_idle_sigs[2] = AESL_inst_myproject.dense_array_ap_fixed_64u_array_ap_fixed_16_6_5_3_0_32u_config4_U0.ap_idle;
assign inst_block_sigs[2] = (AESL_inst_myproject.dense_array_ap_fixed_64u_array_ap_fixed_16_6_5_3_0_32u_config4_U0.ap_done & ~AESL_inst_myproject.dense_array_ap_fixed_64u_array_ap_fixed_16_6_5_3_0_32u_config4_U0.ap_continue) | ~AESL_inst_myproject.dense_array_ap_fixed_64u_array_ap_fixed_16_6_5_3_0_32u_config4_U0.layer3_out_blk_n | ~AESL_inst_myproject.dense_array_ap_fixed_64u_array_ap_fixed_16_6_5_3_0_32u_config4_U0.layer4_out_blk_n;
assign inst_idle_sigs[3] = AESL_inst_myproject.relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config5_U0.ap_idle;
assign inst_block_sigs[3] = (AESL_inst_myproject.relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config5_U0.ap_done & ~AESL_inst_myproject.relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config5_U0.ap_continue) | ~AESL_inst_myproject.relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config5_U0.layer4_out_blk_n | ~AESL_inst_myproject.relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config5_U0.layer5_out_blk_n;
assign inst_idle_sigs[4] = AESL_inst_myproject.dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_config6_U0.ap_idle;
assign inst_block_sigs[4] = (AESL_inst_myproject.dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_config6_U0.ap_done & ~AESL_inst_myproject.dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_config6_U0.ap_continue) | ~AESL_inst_myproject.dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_config6_U0.layer5_out_blk_n | ~AESL_inst_myproject.dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_config6_U0.layer6_out_blk_n;
assign inst_idle_sigs[5] = AESL_inst_myproject.relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config7_U0.ap_idle;
assign inst_block_sigs[5] = (AESL_inst_myproject.relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config7_U0.ap_done & ~AESL_inst_myproject.relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config7_U0.ap_continue) | ~AESL_inst_myproject.relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config7_U0.layer6_out_blk_n | ~AESL_inst_myproject.relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config7_U0.layer7_out_blk_n;
assign inst_idle_sigs[6] = AESL_inst_myproject.dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_5u_config8_U0.ap_idle;
assign inst_block_sigs[6] = (AESL_inst_myproject.dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_5u_config8_U0.ap_done & ~AESL_inst_myproject.dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_5u_config8_U0.ap_continue) | ~AESL_inst_myproject.dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_5u_config8_U0.layer7_out_blk_n | ~AESL_inst_myproject.dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_5u_config8_U0.layer8_out_blk_n;
assign inst_idle_sigs[7] = AESL_inst_myproject.softmax_array_array_ap_fixed_16_6_5_3_0_5u_softmax_config9_U0.ap_idle;
assign inst_block_sigs[7] = (AESL_inst_myproject.softmax_array_array_ap_fixed_16_6_5_3_0_5u_softmax_config9_U0.ap_done & ~AESL_inst_myproject.softmax_array_array_ap_fixed_16_6_5_3_0_5u_softmax_config9_U0.ap_continue) | ~AESL_inst_myproject.softmax_array_array_ap_fixed_16_6_5_3_0_5u_softmax_config9_U0.grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_5u_softmax_config9_s_fu_26.layer8_out_blk_n;

assign inst_idle_sigs[8] = 1'b0;
assign inst_idle_sigs[9] = AESL_inst_myproject.dense_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_64u_config2_U0.ap_idle;
assign inst_idle_sigs[10] = AESL_inst_myproject.softmax_array_array_ap_fixed_16_6_5_3_0_5u_softmax_config9_U0.ap_idle;
assign inst_idle_sigs[11] = AESL_inst_myproject.softmax_array_array_ap_fixed_16_6_5_3_0_5u_softmax_config9_U0.grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_5u_softmax_config9_s_fu_26.ap_idle;

AESL_deadlock_idx0_monitor AESL_deadlock_idx0_monitor_U (
    .clock(kernel_monitor_clock),
    .reset(kernel_monitor_reset),
    .axis_block_sigs(axis_block_sigs),
    .inst_idle_sigs(inst_idle_sigs),
    .inst_block_sigs(inst_block_sigs),
    .block(kernel_block)
);


initial begin : trigger_axis_deadlock
reg block_delay;
    block_delay = 0;
    while(1) begin
        @(posedge kernel_monitor_clock);
    if (kernel_block == 1'b1 && block_delay == 1'b0)
        block_delay = kernel_block;
    end
end

endmodule
