// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module myproject_dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_config6_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer5_out_dout,
        layer5_out_empty_n,
        layer5_out_read,
        layer5_out_num_data_valid,
        layer5_out_fifo_cap,
        layer6_out_din,
        layer6_out_full_n,
        layer6_out_write,
        layer6_out_num_data_valid,
        layer6_out_fifo_cap
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [511:0] layer5_out_dout;
input   layer5_out_empty_n;
output   layer5_out_read;
input  [1:0] layer5_out_num_data_valid;
input  [1:0] layer5_out_fifo_cap;
output  [511:0] layer6_out_din;
input   layer6_out_full_n;
output   layer6_out_write;
input  [1:0] layer6_out_num_data_valid;
input  [1:0] layer6_out_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer5_out_read;
reg layer6_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer5_out_blk_n;
reg    layer6_out_blk_n;
wire    ap_CS_fsm_state3;
wire   [15:0] data_fu_197_p1;
reg   [15:0] data_reg_676;
reg    ap_block_state1;
reg   [15:0] data_123_reg_681;
reg   [15:0] data_93_reg_686;
reg   [15:0] data_94_reg_691;
reg   [15:0] data_95_reg_696;
reg   [15:0] data_96_reg_701;
reg   [15:0] data_97_reg_706;
reg   [15:0] data_98_reg_711;
reg   [15:0] data_99_reg_716;
reg   [15:0] data_100_reg_721;
reg   [15:0] data_101_reg_726;
reg   [15:0] data_102_reg_731;
reg   [15:0] data_103_reg_736;
reg   [15:0] data_104_reg_741;
reg   [15:0] data_105_reg_746;
reg   [15:0] data_106_reg_751;
reg   [15:0] data_107_reg_756;
reg   [15:0] data_108_reg_761;
reg   [15:0] data_109_reg_766;
reg   [15:0] data_110_reg_771;
reg   [15:0] data_111_reg_776;
reg   [15:0] data_112_reg_781;
reg   [15:0] data_113_reg_786;
reg   [15:0] data_114_reg_791;
reg   [15:0] data_115_reg_796;
reg   [15:0] data_116_reg_801;
reg   [15:0] data_117_reg_806;
reg   [15:0] data_118_reg_811;
reg   [15:0] data_119_reg_816;
reg   [15:0] data_120_reg_821;
reg   [15:0] data_121_reg_826;
reg   [15:0] data_122_reg_831;
reg   [15:0] res_reg_836;
wire    ap_CS_fsm_state2;
reg   [15:0] res_1_reg_841;
reg   [15:0] res_2_reg_846;
reg   [15:0] res_3_reg_851;
reg   [15:0] res_4_reg_856;
reg   [15:0] res_5_reg_861;
reg   [15:0] res_6_reg_866;
reg   [15:0] res_7_reg_871;
reg   [15:0] res_8_reg_876;
reg   [15:0] res_9_reg_881;
reg   [15:0] res_32_reg_886;
reg   [15:0] res_33_reg_891;
reg   [15:0] res_34_reg_896;
reg   [15:0] res_35_reg_901;
reg   [15:0] res_36_reg_906;
reg   [15:0] res_37_reg_911;
reg   [15:0] res_38_reg_916;
reg   [15:0] res_39_reg_921;
reg   [15:0] res_40_reg_926;
reg   [15:0] res_41_reg_931;
reg   [15:0] res_42_reg_936;
reg   [15:0] res_43_reg_941;
reg   [15:0] res_44_reg_946;
reg   [15:0] res_45_reg_951;
reg   [15:0] res_46_reg_956;
reg   [15:0] res_47_reg_961;
reg   [15:0] res_48_reg_966;
reg   [15:0] res_49_reg_971;
reg   [15:0] res_50_reg_976;
reg   [15:0] res_51_reg_981;
reg   [15:0] res_52_reg_986;
reg   [15:0] res_53_reg_991;
wire    call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_ready;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_0;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_1;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_2;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_3;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_4;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_5;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_6;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_7;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_8;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_9;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_10;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_11;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_12;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_13;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_14;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_15;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_16;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_17;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_18;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_19;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_20;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_21;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_22;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_23;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_24;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_25;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_26;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_27;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_28;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_29;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_30;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_31;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
end

myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161(
    .ap_ready(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_ready),
    .data_0_val(data_reg_676),
    .data_1_val(data_123_reg_681),
    .data_2_val(data_93_reg_686),
    .data_3_val(data_94_reg_691),
    .data_4_val(data_95_reg_696),
    .data_5_val(data_96_reg_701),
    .data_6_val(data_97_reg_706),
    .data_7_val(data_98_reg_711),
    .data_8_val(data_99_reg_716),
    .data_9_val(data_100_reg_721),
    .data_10_val(data_101_reg_726),
    .data_11_val(data_102_reg_731),
    .data_12_val(data_103_reg_736),
    .data_13_val(data_104_reg_741),
    .data_14_val(data_105_reg_746),
    .data_15_val(data_106_reg_751),
    .data_16_val(data_107_reg_756),
    .data_17_val(data_108_reg_761),
    .data_18_val(data_109_reg_766),
    .data_19_val(data_110_reg_771),
    .data_20_val(data_111_reg_776),
    .data_21_val(data_112_reg_781),
    .data_22_val(data_113_reg_786),
    .data_23_val(data_114_reg_791),
    .data_24_val(data_115_reg_796),
    .data_25_val(data_116_reg_801),
    .data_26_val(data_117_reg_806),
    .data_27_val(data_118_reg_811),
    .data_28_val(data_119_reg_816),
    .data_29_val(data_120_reg_821),
    .data_30_val(data_121_reg_826),
    .data_31_val(data_122_reg_831),
    .ap_return_0(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_0),
    .ap_return_1(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_1),
    .ap_return_2(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_2),
    .ap_return_3(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_3),
    .ap_return_4(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_4),
    .ap_return_5(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_5),
    .ap_return_6(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_6),
    .ap_return_7(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_7),
    .ap_return_8(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_8),
    .ap_return_9(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_9),
    .ap_return_10(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_10),
    .ap_return_11(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_11),
    .ap_return_12(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_12),
    .ap_return_13(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_13),
    .ap_return_14(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_14),
    .ap_return_15(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_15),
    .ap_return_16(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_16),
    .ap_return_17(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_17),
    .ap_return_18(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_18),
    .ap_return_19(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_19),
    .ap_return_20(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_20),
    .ap_return_21(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_21),
    .ap_return_22(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_22),
    .ap_return_23(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_23),
    .ap_return_24(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_24),
    .ap_return_25(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_25),
    .ap_return_26(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_26),
    .ap_return_27(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_27),
    .ap_return_28(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_28),
    .ap_return_29(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_29),
    .ap_return_30(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_30),
    .ap_return_31(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_31),
    .ap_rst(ap_rst)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((layer6_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        data_100_reg_721 <= {{layer5_out_dout[159:144]}};
        data_101_reg_726 <= {{layer5_out_dout[175:160]}};
        data_102_reg_731 <= {{layer5_out_dout[191:176]}};
        data_103_reg_736 <= {{layer5_out_dout[207:192]}};
        data_104_reg_741 <= {{layer5_out_dout[223:208]}};
        data_105_reg_746 <= {{layer5_out_dout[239:224]}};
        data_106_reg_751 <= {{layer5_out_dout[255:240]}};
        data_107_reg_756 <= {{layer5_out_dout[271:256]}};
        data_108_reg_761 <= {{layer5_out_dout[287:272]}};
        data_109_reg_766 <= {{layer5_out_dout[303:288]}};
        data_110_reg_771 <= {{layer5_out_dout[319:304]}};
        data_111_reg_776 <= {{layer5_out_dout[335:320]}};
        data_112_reg_781 <= {{layer5_out_dout[351:336]}};
        data_113_reg_786 <= {{layer5_out_dout[367:352]}};
        data_114_reg_791 <= {{layer5_out_dout[383:368]}};
        data_115_reg_796 <= {{layer5_out_dout[399:384]}};
        data_116_reg_801 <= {{layer5_out_dout[415:400]}};
        data_117_reg_806 <= {{layer5_out_dout[431:416]}};
        data_118_reg_811 <= {{layer5_out_dout[447:432]}};
        data_119_reg_816 <= {{layer5_out_dout[463:448]}};
        data_120_reg_821 <= {{layer5_out_dout[479:464]}};
        data_121_reg_826 <= {{layer5_out_dout[495:480]}};
        data_122_reg_831 <= {{layer5_out_dout[511:496]}};
        data_123_reg_681 <= {{layer5_out_dout[31:16]}};
        data_93_reg_686 <= {{layer5_out_dout[47:32]}};
        data_94_reg_691 <= {{layer5_out_dout[63:48]}};
        data_95_reg_696 <= {{layer5_out_dout[79:64]}};
        data_96_reg_701 <= {{layer5_out_dout[95:80]}};
        data_97_reg_706 <= {{layer5_out_dout[111:96]}};
        data_98_reg_711 <= {{layer5_out_dout[127:112]}};
        data_99_reg_716 <= {{layer5_out_dout[143:128]}};
        data_reg_676 <= data_fu_197_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        res_1_reg_841 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_1;
        res_2_reg_846 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_2;
        res_32_reg_886 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_10;
        res_33_reg_891 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_11;
        res_34_reg_896 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_12;
        res_35_reg_901 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_13;
        res_36_reg_906 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_14;
        res_37_reg_911 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_15;
        res_38_reg_916 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_16;
        res_39_reg_921 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_17;
        res_3_reg_851 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_3;
        res_40_reg_926 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_18;
        res_41_reg_931 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_19;
        res_42_reg_936 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_20;
        res_43_reg_941 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_21;
        res_44_reg_946 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_22;
        res_45_reg_951 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_23;
        res_46_reg_956 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_24;
        res_47_reg_961 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_25;
        res_48_reg_966 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_26;
        res_49_reg_971 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_27;
        res_4_reg_856 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_4;
        res_50_reg_976 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_28;
        res_51_reg_981 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_29;
        res_52_reg_986 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_30;
        res_53_reg_991 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_31;
        res_5_reg_861 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_5;
        res_6_reg_866 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_6;
        res_7_reg_871 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_7;
        res_8_reg_876 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_8;
        res_9_reg_881 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_9;
        res_reg_836 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_fu_161_ap_return_0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((layer6_out_full_n == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((layer6_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((layer6_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer5_out_blk_n = layer5_out_empty_n;
    end else begin
        layer5_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        layer5_out_read = 1'b1;
    end else begin
        layer5_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        layer6_out_blk_n = layer6_out_full_n;
    end else begin
        layer6_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((layer6_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        layer6_out_write = 1'b1;
    end else begin
        layer6_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((layer6_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (layer5_out_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign data_fu_197_p1 = layer5_out_dout[15:0];

assign layer6_out_din = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{res_53_reg_991}, {res_52_reg_986}}, {res_51_reg_981}}, {res_50_reg_976}}, {res_49_reg_971}}, {res_48_reg_966}}, {res_47_reg_961}}, {res_46_reg_956}}, {res_45_reg_951}}, {res_44_reg_946}}, {res_43_reg_941}}, {res_42_reg_936}}, {res_41_reg_931}}, {res_40_reg_926}}, {res_39_reg_921}}, {res_38_reg_916}}, {res_37_reg_911}}, {res_36_reg_906}}, {res_35_reg_901}}, {res_34_reg_896}}, {res_33_reg_891}}, {res_32_reg_886}}, {res_9_reg_881}}, {res_8_reg_876}}, {res_7_reg_871}}, {res_6_reg_866}}, {res_5_reg_861}}, {res_4_reg_856}}, {res_3_reg_851}}, {res_2_reg_846}}, {res_1_reg_841}}, {res_reg_836}};

assign start_out = real_start;

endmodule //myproject_dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_config6_s
