// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module myproject_relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config7_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer6_out_dout,
        layer6_out_empty_n,
        layer6_out_read,
        layer6_out_num_data_valid,
        layer6_out_fifo_cap,
        layer7_out_din,
        layer7_out_full_n,
        layer7_out_write,
        layer7_out_num_data_valid,
        layer7_out_fifo_cap
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [511:0] layer6_out_dout;
input   layer6_out_empty_n;
output   layer6_out_read;
input  [1:0] layer6_out_num_data_valid;
input  [1:0] layer6_out_fifo_cap;
output  [511:0] layer7_out_din;
input   layer7_out_full_n;
output   layer7_out_write;
input  [1:0] layer7_out_num_data_valid;
input  [1:0] layer7_out_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer6_out_read;
reg layer7_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer6_out_blk_n;
reg    layer7_out_blk_n;
reg    ap_block_state1;
wire   [15:0] trunc_ln44_fu_227_p1;
wire   [0:0] icmp_ln51_fu_855_p2;
wire   [14:0] trunc_ln44_156_fu_231_p1;
wire   [14:0] select_ln51_fu_861_p3;
wire   [15:0] trunc_ln44_64_fu_235_p4;
wire   [0:0] icmp_ln51_64_fu_873_p2;
wire   [14:0] trunc_ln44_s_fu_245_p4;
wire   [14:0] select_ln51_64_fu_879_p3;
wire   [15:0] trunc_ln44_65_fu_255_p4;
wire   [0:0] icmp_ln51_65_fu_891_p2;
wire   [14:0] trunc_ln44_125_fu_265_p4;
wire   [14:0] select_ln51_65_fu_897_p3;
wire   [15:0] trunc_ln44_66_fu_275_p4;
wire   [0:0] icmp_ln51_66_fu_909_p2;
wire   [14:0] trunc_ln44_126_fu_285_p4;
wire   [14:0] select_ln51_66_fu_915_p3;
wire   [15:0] trunc_ln44_67_fu_295_p4;
wire   [0:0] icmp_ln51_67_fu_927_p2;
wire   [14:0] trunc_ln44_127_fu_305_p4;
wire   [14:0] select_ln51_67_fu_933_p3;
wire   [15:0] trunc_ln44_68_fu_315_p4;
wire   [0:0] icmp_ln51_68_fu_945_p2;
wire   [14:0] trunc_ln44_128_fu_325_p4;
wire   [14:0] select_ln51_68_fu_951_p3;
wire   [15:0] trunc_ln44_69_fu_335_p4;
wire   [0:0] icmp_ln51_69_fu_963_p2;
wire   [14:0] trunc_ln44_129_fu_345_p4;
wire   [14:0] select_ln51_69_fu_969_p3;
wire   [15:0] trunc_ln44_70_fu_355_p4;
wire   [0:0] icmp_ln51_70_fu_981_p2;
wire   [14:0] trunc_ln44_130_fu_365_p4;
wire   [14:0] select_ln51_70_fu_987_p3;
wire   [15:0] trunc_ln44_71_fu_375_p4;
wire   [0:0] icmp_ln51_71_fu_999_p2;
wire   [14:0] trunc_ln44_131_fu_385_p4;
wire   [14:0] select_ln51_71_fu_1005_p3;
wire   [15:0] trunc_ln44_72_fu_395_p4;
wire   [0:0] icmp_ln51_72_fu_1017_p2;
wire   [14:0] trunc_ln44_132_fu_405_p4;
wire   [14:0] select_ln51_72_fu_1023_p3;
wire   [15:0] trunc_ln44_73_fu_415_p4;
wire   [0:0] icmp_ln51_73_fu_1035_p2;
wire   [14:0] trunc_ln44_133_fu_425_p4;
wire   [14:0] select_ln51_73_fu_1041_p3;
wire   [15:0] trunc_ln44_74_fu_435_p4;
wire   [0:0] icmp_ln51_74_fu_1053_p2;
wire   [14:0] trunc_ln44_134_fu_445_p4;
wire   [14:0] select_ln51_74_fu_1059_p3;
wire   [15:0] trunc_ln44_75_fu_455_p4;
wire   [0:0] icmp_ln51_75_fu_1071_p2;
wire   [14:0] trunc_ln44_135_fu_465_p4;
wire   [14:0] select_ln51_75_fu_1077_p3;
wire   [15:0] trunc_ln44_76_fu_475_p4;
wire   [0:0] icmp_ln51_76_fu_1089_p2;
wire   [14:0] trunc_ln44_136_fu_485_p4;
wire   [14:0] select_ln51_76_fu_1095_p3;
wire   [15:0] trunc_ln44_77_fu_495_p4;
wire   [0:0] icmp_ln51_77_fu_1107_p2;
wire   [14:0] trunc_ln44_137_fu_505_p4;
wire   [14:0] select_ln51_77_fu_1113_p3;
wire   [15:0] trunc_ln44_78_fu_515_p4;
wire   [0:0] icmp_ln51_78_fu_1125_p2;
wire   [14:0] trunc_ln44_138_fu_525_p4;
wire   [14:0] select_ln51_78_fu_1131_p3;
wire   [15:0] trunc_ln44_79_fu_535_p4;
wire   [0:0] icmp_ln51_79_fu_1143_p2;
wire   [14:0] trunc_ln44_139_fu_545_p4;
wire   [14:0] select_ln51_79_fu_1149_p3;
wire   [15:0] trunc_ln44_80_fu_555_p4;
wire   [0:0] icmp_ln51_80_fu_1161_p2;
wire   [14:0] trunc_ln44_140_fu_565_p4;
wire   [14:0] select_ln51_80_fu_1167_p3;
wire   [15:0] trunc_ln44_81_fu_575_p4;
wire   [0:0] icmp_ln51_81_fu_1179_p2;
wire   [14:0] trunc_ln44_141_fu_585_p4;
wire   [14:0] select_ln51_81_fu_1185_p3;
wire   [15:0] trunc_ln44_82_fu_595_p4;
wire   [0:0] icmp_ln51_82_fu_1197_p2;
wire   [14:0] trunc_ln44_142_fu_605_p4;
wire   [14:0] select_ln51_82_fu_1203_p3;
wire   [15:0] trunc_ln44_83_fu_615_p4;
wire   [0:0] icmp_ln51_83_fu_1215_p2;
wire   [14:0] trunc_ln44_143_fu_625_p4;
wire   [14:0] select_ln51_83_fu_1221_p3;
wire   [15:0] trunc_ln44_84_fu_635_p4;
wire   [0:0] icmp_ln51_84_fu_1233_p2;
wire   [14:0] trunc_ln44_144_fu_645_p4;
wire   [14:0] select_ln51_84_fu_1239_p3;
wire   [15:0] trunc_ln44_85_fu_655_p4;
wire   [0:0] icmp_ln51_85_fu_1251_p2;
wire   [14:0] trunc_ln44_145_fu_665_p4;
wire   [14:0] select_ln51_85_fu_1257_p3;
wire   [15:0] trunc_ln44_86_fu_675_p4;
wire   [0:0] icmp_ln51_86_fu_1269_p2;
wire   [14:0] trunc_ln44_146_fu_685_p4;
wire   [14:0] select_ln51_86_fu_1275_p3;
wire   [15:0] trunc_ln44_87_fu_695_p4;
wire   [0:0] icmp_ln51_87_fu_1287_p2;
wire   [14:0] trunc_ln44_147_fu_705_p4;
wire   [14:0] select_ln51_87_fu_1293_p3;
wire   [15:0] trunc_ln44_88_fu_715_p4;
wire   [0:0] icmp_ln51_88_fu_1305_p2;
wire   [14:0] trunc_ln44_148_fu_725_p4;
wire   [14:0] select_ln51_88_fu_1311_p3;
wire   [15:0] trunc_ln44_89_fu_735_p4;
wire   [0:0] icmp_ln51_89_fu_1323_p2;
wire   [14:0] trunc_ln44_149_fu_745_p4;
wire   [14:0] select_ln51_89_fu_1329_p3;
wire   [15:0] trunc_ln44_90_fu_755_p4;
wire   [0:0] icmp_ln51_90_fu_1341_p2;
wire   [14:0] trunc_ln44_150_fu_765_p4;
wire   [14:0] select_ln51_90_fu_1347_p3;
wire   [15:0] trunc_ln44_91_fu_775_p4;
wire   [0:0] icmp_ln51_91_fu_1359_p2;
wire   [14:0] trunc_ln44_151_fu_785_p4;
wire   [14:0] select_ln51_91_fu_1365_p3;
wire   [15:0] trunc_ln44_92_fu_795_p4;
wire   [0:0] icmp_ln51_92_fu_1377_p2;
wire   [14:0] trunc_ln44_152_fu_805_p4;
wire   [14:0] select_ln51_92_fu_1383_p3;
wire   [15:0] trunc_ln44_93_fu_815_p4;
wire   [0:0] icmp_ln51_93_fu_1395_p2;
wire   [14:0] trunc_ln44_153_fu_825_p4;
wire   [14:0] select_ln51_93_fu_1401_p3;
wire   [15:0] trunc_ln44_94_fu_835_p4;
wire   [0:0] icmp_ln51_94_fu_1413_p2;
wire   [14:0] trunc_ln5_fu_845_p4;
wire   [14:0] select_ln51_94_fu_1419_p3;
wire   [15:0] zext_ln51_93_fu_1409_p1;
wire   [15:0] zext_ln51_92_fu_1391_p1;
wire   [15:0] zext_ln51_91_fu_1373_p1;
wire   [15:0] zext_ln51_90_fu_1355_p1;
wire   [15:0] zext_ln51_89_fu_1337_p1;
wire   [15:0] zext_ln51_88_fu_1319_p1;
wire   [15:0] zext_ln51_87_fu_1301_p1;
wire   [15:0] zext_ln51_86_fu_1283_p1;
wire   [15:0] zext_ln51_85_fu_1265_p1;
wire   [15:0] zext_ln51_84_fu_1247_p1;
wire   [15:0] zext_ln51_83_fu_1229_p1;
wire   [15:0] zext_ln51_82_fu_1211_p1;
wire   [15:0] zext_ln51_81_fu_1193_p1;
wire   [15:0] zext_ln51_80_fu_1175_p1;
wire   [15:0] zext_ln51_79_fu_1157_p1;
wire   [15:0] zext_ln51_78_fu_1139_p1;
wire   [15:0] zext_ln51_77_fu_1121_p1;
wire   [15:0] zext_ln51_76_fu_1103_p1;
wire   [15:0] zext_ln51_75_fu_1085_p1;
wire   [15:0] zext_ln51_74_fu_1067_p1;
wire   [15:0] zext_ln51_73_fu_1049_p1;
wire   [15:0] zext_ln51_72_fu_1031_p1;
wire   [15:0] zext_ln51_71_fu_1013_p1;
wire   [15:0] zext_ln51_70_fu_995_p1;
wire   [15:0] zext_ln51_69_fu_977_p1;
wire   [15:0] zext_ln51_68_fu_959_p1;
wire   [15:0] zext_ln51_67_fu_941_p1;
wire   [15:0] zext_ln51_66_fu_923_p1;
wire   [15:0] zext_ln51_65_fu_905_p1;
wire   [15:0] zext_ln51_64_fu_887_p1;
wire   [15:0] zext_ln51_fu_869_p1;
wire   [510:0] or_ln57_s_fu_1427_p33;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer6_out_blk_n = layer6_out_empty_n;
    end else begin
        layer6_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        layer6_out_read = 1'b1;
    end else begin
        layer6_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer7_out_blk_n = layer7_out_full_n;
    end else begin
        layer7_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        layer7_out_write = 1'b1;
    end else begin
        layer7_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (layer7_out_full_n == 1'b0) | (layer6_out_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign icmp_ln51_64_fu_873_p2 = (($signed(trunc_ln44_64_fu_235_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_65_fu_891_p2 = (($signed(trunc_ln44_65_fu_255_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_66_fu_909_p2 = (($signed(trunc_ln44_66_fu_275_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_67_fu_927_p2 = (($signed(trunc_ln44_67_fu_295_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_68_fu_945_p2 = (($signed(trunc_ln44_68_fu_315_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_69_fu_963_p2 = (($signed(trunc_ln44_69_fu_335_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_70_fu_981_p2 = (($signed(trunc_ln44_70_fu_355_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_71_fu_999_p2 = (($signed(trunc_ln44_71_fu_375_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_72_fu_1017_p2 = (($signed(trunc_ln44_72_fu_395_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_73_fu_1035_p2 = (($signed(trunc_ln44_73_fu_415_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_74_fu_1053_p2 = (($signed(trunc_ln44_74_fu_435_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_75_fu_1071_p2 = (($signed(trunc_ln44_75_fu_455_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_76_fu_1089_p2 = (($signed(trunc_ln44_76_fu_475_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_77_fu_1107_p2 = (($signed(trunc_ln44_77_fu_495_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_78_fu_1125_p2 = (($signed(trunc_ln44_78_fu_515_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_79_fu_1143_p2 = (($signed(trunc_ln44_79_fu_535_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_80_fu_1161_p2 = (($signed(trunc_ln44_80_fu_555_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_81_fu_1179_p2 = (($signed(trunc_ln44_81_fu_575_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_82_fu_1197_p2 = (($signed(trunc_ln44_82_fu_595_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_83_fu_1215_p2 = (($signed(trunc_ln44_83_fu_615_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_84_fu_1233_p2 = (($signed(trunc_ln44_84_fu_635_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_85_fu_1251_p2 = (($signed(trunc_ln44_85_fu_655_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_86_fu_1269_p2 = (($signed(trunc_ln44_86_fu_675_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_87_fu_1287_p2 = (($signed(trunc_ln44_87_fu_695_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_88_fu_1305_p2 = (($signed(trunc_ln44_88_fu_715_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_89_fu_1323_p2 = (($signed(trunc_ln44_89_fu_735_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_90_fu_1341_p2 = (($signed(trunc_ln44_90_fu_755_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_91_fu_1359_p2 = (($signed(trunc_ln44_91_fu_775_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_92_fu_1377_p2 = (($signed(trunc_ln44_92_fu_795_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_93_fu_1395_p2 = (($signed(trunc_ln44_93_fu_815_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_94_fu_1413_p2 = (($signed(trunc_ln44_94_fu_835_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_855_p2 = (($signed(trunc_ln44_fu_227_p1) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign layer7_out_din = or_ln57_s_fu_1427_p33;

assign or_ln57_s_fu_1427_p33 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{select_ln51_94_fu_1419_p3}, {zext_ln51_93_fu_1409_p1}}, {zext_ln51_92_fu_1391_p1}}, {zext_ln51_91_fu_1373_p1}}, {zext_ln51_90_fu_1355_p1}}, {zext_ln51_89_fu_1337_p1}}, {zext_ln51_88_fu_1319_p1}}, {zext_ln51_87_fu_1301_p1}}, {zext_ln51_86_fu_1283_p1}}, {zext_ln51_85_fu_1265_p1}}, {zext_ln51_84_fu_1247_p1}}, {zext_ln51_83_fu_1229_p1}}, {zext_ln51_82_fu_1211_p1}}, {zext_ln51_81_fu_1193_p1}}, {zext_ln51_80_fu_1175_p1}}, {zext_ln51_79_fu_1157_p1}}, {zext_ln51_78_fu_1139_p1}}, {zext_ln51_77_fu_1121_p1}}, {zext_ln51_76_fu_1103_p1}}, {zext_ln51_75_fu_1085_p1}}, {zext_ln51_74_fu_1067_p1}}, {zext_ln51_73_fu_1049_p1}}, {zext_ln51_72_fu_1031_p1}}, {zext_ln51_71_fu_1013_p1}}, {zext_ln51_70_fu_995_p1}}, {zext_ln51_69_fu_977_p1}}, {zext_ln51_68_fu_959_p1}}, {zext_ln51_67_fu_941_p1}}, {zext_ln51_66_fu_923_p1}}, {zext_ln51_65_fu_905_p1}}, {zext_ln51_64_fu_887_p1}}, {zext_ln51_fu_869_p1}};

assign select_ln51_64_fu_879_p3 = ((icmp_ln51_64_fu_873_p2[0:0] == 1'b1) ? trunc_ln44_s_fu_245_p4 : 15'd0);

assign select_ln51_65_fu_897_p3 = ((icmp_ln51_65_fu_891_p2[0:0] == 1'b1) ? trunc_ln44_125_fu_265_p4 : 15'd0);

assign select_ln51_66_fu_915_p3 = ((icmp_ln51_66_fu_909_p2[0:0] == 1'b1) ? trunc_ln44_126_fu_285_p4 : 15'd0);

assign select_ln51_67_fu_933_p3 = ((icmp_ln51_67_fu_927_p2[0:0] == 1'b1) ? trunc_ln44_127_fu_305_p4 : 15'd0);

assign select_ln51_68_fu_951_p3 = ((icmp_ln51_68_fu_945_p2[0:0] == 1'b1) ? trunc_ln44_128_fu_325_p4 : 15'd0);

assign select_ln51_69_fu_969_p3 = ((icmp_ln51_69_fu_963_p2[0:0] == 1'b1) ? trunc_ln44_129_fu_345_p4 : 15'd0);

assign select_ln51_70_fu_987_p3 = ((icmp_ln51_70_fu_981_p2[0:0] == 1'b1) ? trunc_ln44_130_fu_365_p4 : 15'd0);

assign select_ln51_71_fu_1005_p3 = ((icmp_ln51_71_fu_999_p2[0:0] == 1'b1) ? trunc_ln44_131_fu_385_p4 : 15'd0);

assign select_ln51_72_fu_1023_p3 = ((icmp_ln51_72_fu_1017_p2[0:0] == 1'b1) ? trunc_ln44_132_fu_405_p4 : 15'd0);

assign select_ln51_73_fu_1041_p3 = ((icmp_ln51_73_fu_1035_p2[0:0] == 1'b1) ? trunc_ln44_133_fu_425_p4 : 15'd0);

assign select_ln51_74_fu_1059_p3 = ((icmp_ln51_74_fu_1053_p2[0:0] == 1'b1) ? trunc_ln44_134_fu_445_p4 : 15'd0);

assign select_ln51_75_fu_1077_p3 = ((icmp_ln51_75_fu_1071_p2[0:0] == 1'b1) ? trunc_ln44_135_fu_465_p4 : 15'd0);

assign select_ln51_76_fu_1095_p3 = ((icmp_ln51_76_fu_1089_p2[0:0] == 1'b1) ? trunc_ln44_136_fu_485_p4 : 15'd0);

assign select_ln51_77_fu_1113_p3 = ((icmp_ln51_77_fu_1107_p2[0:0] == 1'b1) ? trunc_ln44_137_fu_505_p4 : 15'd0);

assign select_ln51_78_fu_1131_p3 = ((icmp_ln51_78_fu_1125_p2[0:0] == 1'b1) ? trunc_ln44_138_fu_525_p4 : 15'd0);

assign select_ln51_79_fu_1149_p3 = ((icmp_ln51_79_fu_1143_p2[0:0] == 1'b1) ? trunc_ln44_139_fu_545_p4 : 15'd0);

assign select_ln51_80_fu_1167_p3 = ((icmp_ln51_80_fu_1161_p2[0:0] == 1'b1) ? trunc_ln44_140_fu_565_p4 : 15'd0);

assign select_ln51_81_fu_1185_p3 = ((icmp_ln51_81_fu_1179_p2[0:0] == 1'b1) ? trunc_ln44_141_fu_585_p4 : 15'd0);

assign select_ln51_82_fu_1203_p3 = ((icmp_ln51_82_fu_1197_p2[0:0] == 1'b1) ? trunc_ln44_142_fu_605_p4 : 15'd0);

assign select_ln51_83_fu_1221_p3 = ((icmp_ln51_83_fu_1215_p2[0:0] == 1'b1) ? trunc_ln44_143_fu_625_p4 : 15'd0);

assign select_ln51_84_fu_1239_p3 = ((icmp_ln51_84_fu_1233_p2[0:0] == 1'b1) ? trunc_ln44_144_fu_645_p4 : 15'd0);

assign select_ln51_85_fu_1257_p3 = ((icmp_ln51_85_fu_1251_p2[0:0] == 1'b1) ? trunc_ln44_145_fu_665_p4 : 15'd0);

assign select_ln51_86_fu_1275_p3 = ((icmp_ln51_86_fu_1269_p2[0:0] == 1'b1) ? trunc_ln44_146_fu_685_p4 : 15'd0);

assign select_ln51_87_fu_1293_p3 = ((icmp_ln51_87_fu_1287_p2[0:0] == 1'b1) ? trunc_ln44_147_fu_705_p4 : 15'd0);

assign select_ln51_88_fu_1311_p3 = ((icmp_ln51_88_fu_1305_p2[0:0] == 1'b1) ? trunc_ln44_148_fu_725_p4 : 15'd0);

assign select_ln51_89_fu_1329_p3 = ((icmp_ln51_89_fu_1323_p2[0:0] == 1'b1) ? trunc_ln44_149_fu_745_p4 : 15'd0);

assign select_ln51_90_fu_1347_p3 = ((icmp_ln51_90_fu_1341_p2[0:0] == 1'b1) ? trunc_ln44_150_fu_765_p4 : 15'd0);

assign select_ln51_91_fu_1365_p3 = ((icmp_ln51_91_fu_1359_p2[0:0] == 1'b1) ? trunc_ln44_151_fu_785_p4 : 15'd0);

assign select_ln51_92_fu_1383_p3 = ((icmp_ln51_92_fu_1377_p2[0:0] == 1'b1) ? trunc_ln44_152_fu_805_p4 : 15'd0);

assign select_ln51_93_fu_1401_p3 = ((icmp_ln51_93_fu_1395_p2[0:0] == 1'b1) ? trunc_ln44_153_fu_825_p4 : 15'd0);

assign select_ln51_94_fu_1419_p3 = ((icmp_ln51_94_fu_1413_p2[0:0] == 1'b1) ? trunc_ln5_fu_845_p4 : 15'd0);

assign select_ln51_fu_861_p3 = ((icmp_ln51_fu_855_p2[0:0] == 1'b1) ? trunc_ln44_156_fu_231_p1 : 15'd0);

assign start_out = real_start;

assign trunc_ln44_125_fu_265_p4 = {{layer6_out_dout[46:32]}};

assign trunc_ln44_126_fu_285_p4 = {{layer6_out_dout[62:48]}};

assign trunc_ln44_127_fu_305_p4 = {{layer6_out_dout[78:64]}};

assign trunc_ln44_128_fu_325_p4 = {{layer6_out_dout[94:80]}};

assign trunc_ln44_129_fu_345_p4 = {{layer6_out_dout[110:96]}};

assign trunc_ln44_130_fu_365_p4 = {{layer6_out_dout[126:112]}};

assign trunc_ln44_131_fu_385_p4 = {{layer6_out_dout[142:128]}};

assign trunc_ln44_132_fu_405_p4 = {{layer6_out_dout[158:144]}};

assign trunc_ln44_133_fu_425_p4 = {{layer6_out_dout[174:160]}};

assign trunc_ln44_134_fu_445_p4 = {{layer6_out_dout[190:176]}};

assign trunc_ln44_135_fu_465_p4 = {{layer6_out_dout[206:192]}};

assign trunc_ln44_136_fu_485_p4 = {{layer6_out_dout[222:208]}};

assign trunc_ln44_137_fu_505_p4 = {{layer6_out_dout[238:224]}};

assign trunc_ln44_138_fu_525_p4 = {{layer6_out_dout[254:240]}};

assign trunc_ln44_139_fu_545_p4 = {{layer6_out_dout[270:256]}};

assign trunc_ln44_140_fu_565_p4 = {{layer6_out_dout[286:272]}};

assign trunc_ln44_141_fu_585_p4 = {{layer6_out_dout[302:288]}};

assign trunc_ln44_142_fu_605_p4 = {{layer6_out_dout[318:304]}};

assign trunc_ln44_143_fu_625_p4 = {{layer6_out_dout[334:320]}};

assign trunc_ln44_144_fu_645_p4 = {{layer6_out_dout[350:336]}};

assign trunc_ln44_145_fu_665_p4 = {{layer6_out_dout[366:352]}};

assign trunc_ln44_146_fu_685_p4 = {{layer6_out_dout[382:368]}};

assign trunc_ln44_147_fu_705_p4 = {{layer6_out_dout[398:384]}};

assign trunc_ln44_148_fu_725_p4 = {{layer6_out_dout[414:400]}};

assign trunc_ln44_149_fu_745_p4 = {{layer6_out_dout[430:416]}};

assign trunc_ln44_150_fu_765_p4 = {{layer6_out_dout[446:432]}};

assign trunc_ln44_151_fu_785_p4 = {{layer6_out_dout[462:448]}};

assign trunc_ln44_152_fu_805_p4 = {{layer6_out_dout[478:464]}};

assign trunc_ln44_153_fu_825_p4 = {{layer6_out_dout[494:480]}};

assign trunc_ln44_156_fu_231_p1 = layer6_out_dout[14:0];

assign trunc_ln44_64_fu_235_p4 = {{layer6_out_dout[31:16]}};

assign trunc_ln44_65_fu_255_p4 = {{layer6_out_dout[47:32]}};

assign trunc_ln44_66_fu_275_p4 = {{layer6_out_dout[63:48]}};

assign trunc_ln44_67_fu_295_p4 = {{layer6_out_dout[79:64]}};

assign trunc_ln44_68_fu_315_p4 = {{layer6_out_dout[95:80]}};

assign trunc_ln44_69_fu_335_p4 = {{layer6_out_dout[111:96]}};

assign trunc_ln44_70_fu_355_p4 = {{layer6_out_dout[127:112]}};

assign trunc_ln44_71_fu_375_p4 = {{layer6_out_dout[143:128]}};

assign trunc_ln44_72_fu_395_p4 = {{layer6_out_dout[159:144]}};

assign trunc_ln44_73_fu_415_p4 = {{layer6_out_dout[175:160]}};

assign trunc_ln44_74_fu_435_p4 = {{layer6_out_dout[191:176]}};

assign trunc_ln44_75_fu_455_p4 = {{layer6_out_dout[207:192]}};

assign trunc_ln44_76_fu_475_p4 = {{layer6_out_dout[223:208]}};

assign trunc_ln44_77_fu_495_p4 = {{layer6_out_dout[239:224]}};

assign trunc_ln44_78_fu_515_p4 = {{layer6_out_dout[255:240]}};

assign trunc_ln44_79_fu_535_p4 = {{layer6_out_dout[271:256]}};

assign trunc_ln44_80_fu_555_p4 = {{layer6_out_dout[287:272]}};

assign trunc_ln44_81_fu_575_p4 = {{layer6_out_dout[303:288]}};

assign trunc_ln44_82_fu_595_p4 = {{layer6_out_dout[319:304]}};

assign trunc_ln44_83_fu_615_p4 = {{layer6_out_dout[335:320]}};

assign trunc_ln44_84_fu_635_p4 = {{layer6_out_dout[351:336]}};

assign trunc_ln44_85_fu_655_p4 = {{layer6_out_dout[367:352]}};

assign trunc_ln44_86_fu_675_p4 = {{layer6_out_dout[383:368]}};

assign trunc_ln44_87_fu_695_p4 = {{layer6_out_dout[399:384]}};

assign trunc_ln44_88_fu_715_p4 = {{layer6_out_dout[415:400]}};

assign trunc_ln44_89_fu_735_p4 = {{layer6_out_dout[431:416]}};

assign trunc_ln44_90_fu_755_p4 = {{layer6_out_dout[447:432]}};

assign trunc_ln44_91_fu_775_p4 = {{layer6_out_dout[463:448]}};

assign trunc_ln44_92_fu_795_p4 = {{layer6_out_dout[479:464]}};

assign trunc_ln44_93_fu_815_p4 = {{layer6_out_dout[495:480]}};

assign trunc_ln44_94_fu_835_p4 = {{layer6_out_dout[511:496]}};

assign trunc_ln44_fu_227_p1 = layer6_out_dout[15:0];

assign trunc_ln44_s_fu_245_p4 = {{layer6_out_dout[30:16]}};

assign trunc_ln5_fu_845_p4 = {{layer6_out_dout[510:496]}};

assign zext_ln51_64_fu_887_p1 = select_ln51_64_fu_879_p3;

assign zext_ln51_65_fu_905_p1 = select_ln51_65_fu_897_p3;

assign zext_ln51_66_fu_923_p1 = select_ln51_66_fu_915_p3;

assign zext_ln51_67_fu_941_p1 = select_ln51_67_fu_933_p3;

assign zext_ln51_68_fu_959_p1 = select_ln51_68_fu_951_p3;

assign zext_ln51_69_fu_977_p1 = select_ln51_69_fu_969_p3;

assign zext_ln51_70_fu_995_p1 = select_ln51_70_fu_987_p3;

assign zext_ln51_71_fu_1013_p1 = select_ln51_71_fu_1005_p3;

assign zext_ln51_72_fu_1031_p1 = select_ln51_72_fu_1023_p3;

assign zext_ln51_73_fu_1049_p1 = select_ln51_73_fu_1041_p3;

assign zext_ln51_74_fu_1067_p1 = select_ln51_74_fu_1059_p3;

assign zext_ln51_75_fu_1085_p1 = select_ln51_75_fu_1077_p3;

assign zext_ln51_76_fu_1103_p1 = select_ln51_76_fu_1095_p3;

assign zext_ln51_77_fu_1121_p1 = select_ln51_77_fu_1113_p3;

assign zext_ln51_78_fu_1139_p1 = select_ln51_78_fu_1131_p3;

assign zext_ln51_79_fu_1157_p1 = select_ln51_79_fu_1149_p3;

assign zext_ln51_80_fu_1175_p1 = select_ln51_80_fu_1167_p3;

assign zext_ln51_81_fu_1193_p1 = select_ln51_81_fu_1185_p3;

assign zext_ln51_82_fu_1211_p1 = select_ln51_82_fu_1203_p3;

assign zext_ln51_83_fu_1229_p1 = select_ln51_83_fu_1221_p3;

assign zext_ln51_84_fu_1247_p1 = select_ln51_84_fu_1239_p3;

assign zext_ln51_85_fu_1265_p1 = select_ln51_85_fu_1257_p3;

assign zext_ln51_86_fu_1283_p1 = select_ln51_86_fu_1275_p3;

assign zext_ln51_87_fu_1301_p1 = select_ln51_87_fu_1293_p3;

assign zext_ln51_88_fu_1319_p1 = select_ln51_88_fu_1311_p3;

assign zext_ln51_89_fu_1337_p1 = select_ln51_89_fu_1329_p3;

assign zext_ln51_90_fu_1355_p1 = select_ln51_90_fu_1347_p3;

assign zext_ln51_91_fu_1373_p1 = select_ln51_91_fu_1365_p3;

assign zext_ln51_92_fu_1391_p1 = select_ln51_92_fu_1383_p3;

assign zext_ln51_93_fu_1409_p1 = select_ln51_93_fu_1401_p3;

assign zext_ln51_fu_869_p1 = select_ln51_fu_861_p3;

endmodule //myproject_relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config7_s
