-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_5u_config8_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    layer7_out_dout : IN STD_LOGIC_VECTOR (511 downto 0);
    layer7_out_empty_n : IN STD_LOGIC;
    layer7_out_read : OUT STD_LOGIC;
    layer7_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer7_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    layer8_out_din : OUT STD_LOGIC_VECTOR (79 downto 0);
    layer8_out_full_n : IN STD_LOGIC;
    layer8_out_write : OUT STD_LOGIC;
    layer8_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer8_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of myproject_dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_5u_config8_s is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_6F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101111";
    constant ap_const_lv32_70 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_8F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001111";
    constant ap_const_lv32_90 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010000";
    constant ap_const_lv32_9F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011111";
    constant ap_const_lv32_A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100000";
    constant ap_const_lv32_AF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101111";
    constant ap_const_lv32_B0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110000";
    constant ap_const_lv32_BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111111";
    constant ap_const_lv32_C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000000";
    constant ap_const_lv32_CF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001111";
    constant ap_const_lv32_D0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010000";
    constant ap_const_lv32_DF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011111";
    constant ap_const_lv32_E0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100000";
    constant ap_const_lv32_EF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101111";
    constant ap_const_lv32_F0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110000";
    constant ap_const_lv32_FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111111";
    constant ap_const_lv32_100 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000000";
    constant ap_const_lv32_10F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100001111";
    constant ap_const_lv32_110 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100010000";
    constant ap_const_lv32_11F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100011111";
    constant ap_const_lv32_120 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100100000";
    constant ap_const_lv32_12F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100101111";
    constant ap_const_lv32_130 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100110000";
    constant ap_const_lv32_13F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100111111";
    constant ap_const_lv32_140 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101000000";
    constant ap_const_lv32_14F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101001111";
    constant ap_const_lv32_150 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101010000";
    constant ap_const_lv32_15F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101011111";
    constant ap_const_lv32_160 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101100000";
    constant ap_const_lv32_16F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101101111";
    constant ap_const_lv32_170 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101110000";
    constant ap_const_lv32_17F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101111111";
    constant ap_const_lv32_180 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110000000";
    constant ap_const_lv32_18F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110001111";
    constant ap_const_lv32_190 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110010000";
    constant ap_const_lv32_19F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110011111";
    constant ap_const_lv32_1A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110100000";
    constant ap_const_lv32_1AF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110101111";
    constant ap_const_lv32_1B0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110110000";
    constant ap_const_lv32_1BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110111111";
    constant ap_const_lv32_1C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111000000";
    constant ap_const_lv32_1CF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111001111";
    constant ap_const_lv32_1D0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111010000";
    constant ap_const_lv32_1DF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111011111";
    constant ap_const_lv32_1E0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111100000";
    constant ap_const_lv32_1EF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111101111";
    constant ap_const_lv32_1F0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111110000";
    constant ap_const_lv32_1FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111111111";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal layer7_out_blk_n : STD_LOGIC;
    signal layer8_out_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal data_fu_197_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_reg_541 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal data_93_reg_546 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_63_reg_551 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_64_reg_556 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_65_reg_561 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_66_reg_566 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_67_reg_571 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_68_reg_576 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_69_reg_581 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_70_reg_586 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_71_reg_591 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_72_reg_596 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_73_reg_601 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_74_reg_606 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_75_reg_611 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_76_reg_616 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_77_reg_621 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_78_reg_626 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_79_reg_631 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_80_reg_636 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_81_reg_641 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_82_reg_646 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_83_reg_651 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_84_reg_656 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_85_reg_661 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_86_reg_666 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_87_reg_671 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_88_reg_676 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_89_reg_681 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_90_reg_686 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_91_reg_691 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_92_reg_696 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_reg_701 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal res_1_reg_706 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_2_reg_711 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_3_reg_716 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_4_reg_721 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_161_ap_ready : STD_LOGIC;
    signal call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_161_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_161_ap_return_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_161_ap_return_2 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_161_ap_return_3 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_161_ap_return_4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s IS
    port (
        ap_ready : OUT STD_LOGIC;
        data_0_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_1_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_2_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_3_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_4_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_5_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_6_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_7_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_8_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_9_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_10_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_11_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_12_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_13_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_14_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_15_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_16_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_17_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_18_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_19_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_20_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_21_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_22_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_23_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_24_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_25_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_26_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_27_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_28_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_29_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_30_val : IN STD_LOGIC_VECTOR (15 downto 0);
        data_31_val : IN STD_LOGIC_VECTOR (15 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_rst : IN STD_LOGIC );
    end component;



begin
    call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_161 : component myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s
    port map (
        ap_ready => call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_161_ap_ready,
        data_0_val => data_reg_541,
        data_1_val => data_93_reg_546,
        data_2_val => data_63_reg_551,
        data_3_val => data_64_reg_556,
        data_4_val => data_65_reg_561,
        data_5_val => data_66_reg_566,
        data_6_val => data_67_reg_571,
        data_7_val => data_68_reg_576,
        data_8_val => data_69_reg_581,
        data_9_val => data_70_reg_586,
        data_10_val => data_71_reg_591,
        data_11_val => data_72_reg_596,
        data_12_val => data_73_reg_601,
        data_13_val => data_74_reg_606,
        data_14_val => data_75_reg_611,
        data_15_val => data_76_reg_616,
        data_16_val => data_77_reg_621,
        data_17_val => data_78_reg_626,
        data_18_val => data_79_reg_631,
        data_19_val => data_80_reg_636,
        data_20_val => data_81_reg_641,
        data_21_val => data_82_reg_646,
        data_22_val => data_83_reg_651,
        data_23_val => data_84_reg_656,
        data_24_val => data_85_reg_661,
        data_25_val => data_86_reg_666,
        data_26_val => data_87_reg_671,
        data_27_val => data_88_reg_676,
        data_28_val => data_89_reg_681,
        data_29_val => data_90_reg_686,
        data_30_val => data_91_reg_691,
        data_31_val => data_92_reg_696,
        ap_return_0 => call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_161_ap_return_0,
        ap_return_1 => call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_161_ap_return_1,
        ap_return_2 => call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_161_ap_return_2,
        ap_return_3 => call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_161_ap_return_3,
        ap_return_4 => call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_161_ap_return_4,
        ap_rst => ap_rst);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((layer8_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                data_63_reg_551 <= layer7_out_dout(47 downto 32);
                data_64_reg_556 <= layer7_out_dout(63 downto 48);
                data_65_reg_561 <= layer7_out_dout(79 downto 64);
                data_66_reg_566 <= layer7_out_dout(95 downto 80);
                data_67_reg_571 <= layer7_out_dout(111 downto 96);
                data_68_reg_576 <= layer7_out_dout(127 downto 112);
                data_69_reg_581 <= layer7_out_dout(143 downto 128);
                data_70_reg_586 <= layer7_out_dout(159 downto 144);
                data_71_reg_591 <= layer7_out_dout(175 downto 160);
                data_72_reg_596 <= layer7_out_dout(191 downto 176);
                data_73_reg_601 <= layer7_out_dout(207 downto 192);
                data_74_reg_606 <= layer7_out_dout(223 downto 208);
                data_75_reg_611 <= layer7_out_dout(239 downto 224);
                data_76_reg_616 <= layer7_out_dout(255 downto 240);
                data_77_reg_621 <= layer7_out_dout(271 downto 256);
                data_78_reg_626 <= layer7_out_dout(287 downto 272);
                data_79_reg_631 <= layer7_out_dout(303 downto 288);
                data_80_reg_636 <= layer7_out_dout(319 downto 304);
                data_81_reg_641 <= layer7_out_dout(335 downto 320);
                data_82_reg_646 <= layer7_out_dout(351 downto 336);
                data_83_reg_651 <= layer7_out_dout(367 downto 352);
                data_84_reg_656 <= layer7_out_dout(383 downto 368);
                data_85_reg_661 <= layer7_out_dout(399 downto 384);
                data_86_reg_666 <= layer7_out_dout(415 downto 400);
                data_87_reg_671 <= layer7_out_dout(431 downto 416);
                data_88_reg_676 <= layer7_out_dout(447 downto 432);
                data_89_reg_681 <= layer7_out_dout(463 downto 448);
                data_90_reg_686 <= layer7_out_dout(479 downto 464);
                data_91_reg_691 <= layer7_out_dout(495 downto 480);
                data_92_reg_696 <= layer7_out_dout(511 downto 496);
                data_93_reg_546 <= layer7_out_dout(31 downto 16);
                data_reg_541 <= data_fu_197_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                res_1_reg_706 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_161_ap_return_1;
                res_2_reg_711 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_161_ap_return_2;
                res_3_reg_716 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_161_ap_return_3;
                res_4_reg_721 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_161_ap_return_4;
                res_reg_701 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_161_ap_return_0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, layer8_out_full_n, ap_CS_fsm_state3, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((layer8_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(layer8_out_full_n)
    begin
        if ((layer8_out_full_n = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, layer7_out_empty_n)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (layer7_out_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, layer8_out_full_n, ap_CS_fsm_state3)
    begin
        if (((layer8_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    data_fu_197_p1 <= layer7_out_dout(16 - 1 downto 0);

    internal_ap_ready_assign_proc : process(layer8_out_full_n, ap_CS_fsm_state3)
    begin
        if (((layer8_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    layer7_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, layer7_out_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer7_out_blk_n <= layer7_out_empty_n;
        else 
            layer7_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer7_out_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer7_out_read <= ap_const_logic_1;
        else 
            layer7_out_read <= ap_const_logic_0;
        end if; 
    end process;


    layer8_out_blk_n_assign_proc : process(layer8_out_full_n, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            layer8_out_blk_n <= layer8_out_full_n;
        else 
            layer8_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer8_out_din <= ((((res_4_reg_721 & res_3_reg_716) & res_2_reg_711) & res_1_reg_706) & res_reg_701);

    layer8_out_write_assign_proc : process(layer8_out_full_n, ap_CS_fsm_state3)
    begin
        if (((layer8_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            layer8_out_write <= ap_const_logic_1;
        else 
            layer8_out_write <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
