// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module myproject_dense_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_64u_config2_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        input_1_TDATA,
        input_1_TVALID,
        input_1_TREADY,
        layer2_out_din,
        layer2_out_full_n,
        layer2_out_write,
        layer2_out_num_data_valid,
        layer2_out_fifo_cap
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [255:0] input_1_TDATA;
input   input_1_TVALID;
output   input_1_TREADY;
output  [1023:0] layer2_out_din;
input   layer2_out_full_n;
output   layer2_out_write;
input  [1:0] layer2_out_num_data_valid;
input  [1:0] layer2_out_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer2_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    input_1_TDATA_blk_n;
reg    layer2_out_blk_n;
wire    ap_CS_fsm_state2;
reg   [15:0] res_reg_558;
reg    ap_block_state1;
reg   [15:0] res_1_reg_563;
reg   [15:0] res_2_reg_568;
reg   [15:0] res_3_reg_573;
reg   [15:0] res_4_reg_578;
reg   [15:0] res_5_reg_583;
reg   [15:0] res_6_reg_588;
reg   [15:0] res_7_reg_593;
reg   [15:0] res_8_reg_598;
reg   [15:0] res_9_reg_603;
reg   [15:0] res_54_reg_608;
reg   [15:0] res_55_reg_613;
reg   [15:0] res_56_reg_618;
reg   [15:0] res_57_reg_623;
reg   [15:0] res_58_reg_628;
reg   [15:0] res_59_reg_633;
reg   [15:0] res_60_reg_638;
reg   [15:0] res_61_reg_643;
reg   [15:0] res_62_reg_648;
reg   [15:0] res_63_reg_653;
reg   [15:0] res_64_reg_658;
reg   [15:0] res_65_reg_663;
reg   [15:0] res_66_reg_668;
reg   [15:0] res_67_reg_673;
reg   [15:0] res_68_reg_678;
reg   [15:0] res_69_reg_683;
reg   [15:0] res_70_reg_688;
reg   [15:0] res_71_reg_693;
reg   [15:0] res_72_reg_698;
reg   [15:0] res_73_reg_703;
reg   [15:0] res_74_reg_708;
reg   [15:0] res_75_reg_713;
reg   [15:0] res_76_reg_718;
reg   [15:0] res_77_reg_723;
reg   [15:0] res_78_reg_728;
reg   [15:0] res_79_reg_733;
reg   [15:0] res_80_reg_738;
reg   [15:0] res_81_reg_743;
reg   [15:0] res_82_reg_748;
reg   [15:0] res_83_reg_753;
reg   [15:0] res_84_reg_758;
reg   [15:0] res_85_reg_763;
reg   [15:0] res_86_reg_768;
reg   [15:0] res_87_reg_773;
reg   [15:0] res_88_reg_778;
reg   [15:0] res_89_reg_783;
reg   [15:0] res_90_reg_788;
reg   [15:0] res_91_reg_793;
reg   [15:0] res_92_reg_798;
reg   [15:0] res_93_reg_803;
reg   [15:0] res_94_reg_808;
reg   [15:0] res_95_reg_813;
reg   [15:0] res_96_reg_818;
reg   [15:0] res_97_reg_823;
reg   [15:0] res_98_reg_828;
reg   [15:0] res_99_reg_833;
reg   [15:0] res_100_reg_838;
reg   [15:0] res_101_reg_843;
reg   [15:0] res_102_reg_848;
reg   [15:0] res_103_reg_853;
reg   [15:0] res_104_reg_858;
reg   [15:0] res_105_reg_863;
reg   [15:0] res_106_reg_868;
reg   [15:0] res_107_reg_873;
wire    call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_ready;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_0_val;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_1_val;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_2_val;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_3_val;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_4_val;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_5_val;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_6_val;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_7_val;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_8_val;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_9_val;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_10_val;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_11_val;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_12_val;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_13_val;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_14_val;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_15_val;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_0;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_1;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_2;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_3;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_4;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_5;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_6;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_7;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_8;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_9;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_10;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_11;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_12;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_13;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_14;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_15;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_16;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_17;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_18;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_19;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_20;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_21;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_22;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_23;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_24;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_25;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_26;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_27;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_28;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_29;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_30;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_31;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_32;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_33;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_34;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_35;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_36;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_37;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_38;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_39;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_40;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_41;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_42;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_43;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_44;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_45;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_46;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_47;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_48;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_49;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_50;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_51;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_52;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_53;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_54;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_55;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_56;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_57;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_58;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_59;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_60;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_61;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_62;
wire   [15:0] call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_63;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    regslice_both_input_1_U_apdone_blk;
wire   [255:0] input_1_TDATA_int_regslice;
wire    input_1_TVALID_int_regslice;
reg    input_1_TREADY_int_regslice;
wire    regslice_both_input_1_U_ack_in;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
end

myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73(
    .ap_ready(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_ready),
    .data_0_val(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_0_val),
    .data_1_val(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_1_val),
    .data_2_val(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_2_val),
    .data_3_val(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_3_val),
    .data_4_val(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_4_val),
    .data_5_val(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_5_val),
    .data_6_val(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_6_val),
    .data_7_val(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_7_val),
    .data_8_val(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_8_val),
    .data_9_val(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_9_val),
    .data_10_val(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_10_val),
    .data_11_val(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_11_val),
    .data_12_val(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_12_val),
    .data_13_val(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_13_val),
    .data_14_val(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_14_val),
    .data_15_val(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_15_val),
    .ap_return_0(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_0),
    .ap_return_1(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_1),
    .ap_return_2(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_2),
    .ap_return_3(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_3),
    .ap_return_4(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_4),
    .ap_return_5(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_5),
    .ap_return_6(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_6),
    .ap_return_7(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_7),
    .ap_return_8(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_8),
    .ap_return_9(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_9),
    .ap_return_10(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_10),
    .ap_return_11(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_11),
    .ap_return_12(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_12),
    .ap_return_13(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_13),
    .ap_return_14(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_14),
    .ap_return_15(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_15),
    .ap_return_16(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_16),
    .ap_return_17(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_17),
    .ap_return_18(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_18),
    .ap_return_19(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_19),
    .ap_return_20(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_20),
    .ap_return_21(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_21),
    .ap_return_22(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_22),
    .ap_return_23(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_23),
    .ap_return_24(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_24),
    .ap_return_25(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_25),
    .ap_return_26(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_26),
    .ap_return_27(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_27),
    .ap_return_28(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_28),
    .ap_return_29(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_29),
    .ap_return_30(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_30),
    .ap_return_31(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_31),
    .ap_return_32(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_32),
    .ap_return_33(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_33),
    .ap_return_34(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_34),
    .ap_return_35(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_35),
    .ap_return_36(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_36),
    .ap_return_37(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_37),
    .ap_return_38(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_38),
    .ap_return_39(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_39),
    .ap_return_40(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_40),
    .ap_return_41(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_41),
    .ap_return_42(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_42),
    .ap_return_43(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_43),
    .ap_return_44(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_44),
    .ap_return_45(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_45),
    .ap_return_46(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_46),
    .ap_return_47(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_47),
    .ap_return_48(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_48),
    .ap_return_49(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_49),
    .ap_return_50(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_50),
    .ap_return_51(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_51),
    .ap_return_52(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_52),
    .ap_return_53(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_53),
    .ap_return_54(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_54),
    .ap_return_55(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_55),
    .ap_return_56(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_56),
    .ap_return_57(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_57),
    .ap_return_58(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_58),
    .ap_return_59(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_59),
    .ap_return_60(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_60),
    .ap_return_61(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_61),
    .ap_return_62(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_62),
    .ap_return_63(call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_63),
    .ap_rst(ap_rst)
);

myproject_regslice_both #(
    .DataWidth( 256 ))
regslice_both_input_1_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(input_1_TDATA),
    .vld_in(input_1_TVALID),
    .ack_in(regslice_both_input_1_U_ack_in),
    .data_out(input_1_TDATA_int_regslice),
    .vld_out(input_1_TVALID_int_regslice),
    .ack_out(input_1_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_1_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((layer2_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        res_100_reg_838 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_56;
        res_101_reg_843 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_57;
        res_102_reg_848 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_58;
        res_103_reg_853 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_59;
        res_104_reg_858 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_60;
        res_105_reg_863 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_61;
        res_106_reg_868 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_62;
        res_107_reg_873 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_63;
        res_1_reg_563 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_1;
        res_2_reg_568 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_2;
        res_3_reg_573 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_3;
        res_4_reg_578 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_4;
        res_54_reg_608 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_10;
        res_55_reg_613 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_11;
        res_56_reg_618 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_12;
        res_57_reg_623 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_13;
        res_58_reg_628 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_14;
        res_59_reg_633 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_15;
        res_5_reg_583 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_5;
        res_60_reg_638 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_16;
        res_61_reg_643 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_17;
        res_62_reg_648 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_18;
        res_63_reg_653 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_19;
        res_64_reg_658 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_20;
        res_65_reg_663 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_21;
        res_66_reg_668 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_22;
        res_67_reg_673 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_23;
        res_68_reg_678 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_24;
        res_69_reg_683 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_25;
        res_6_reg_588 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_6;
        res_70_reg_688 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_26;
        res_71_reg_693 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_27;
        res_72_reg_698 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_28;
        res_73_reg_703 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_29;
        res_74_reg_708 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_30;
        res_75_reg_713 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_31;
        res_76_reg_718 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_32;
        res_77_reg_723 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_33;
        res_78_reg_728 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_34;
        res_79_reg_733 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_35;
        res_7_reg_593 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_7;
        res_80_reg_738 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_36;
        res_81_reg_743 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_37;
        res_82_reg_748 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_38;
        res_83_reg_753 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_39;
        res_84_reg_758 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_40;
        res_85_reg_763 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_41;
        res_86_reg_768 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_42;
        res_87_reg_773 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_43;
        res_88_reg_778 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_44;
        res_89_reg_783 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_45;
        res_8_reg_598 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_8;
        res_90_reg_788 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_46;
        res_91_reg_793 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_47;
        res_92_reg_798 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_48;
        res_93_reg_803 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_49;
        res_94_reg_808 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_50;
        res_95_reg_813 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_51;
        res_96_reg_818 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_52;
        res_97_reg_823 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_53;
        res_98_reg_828 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_54;
        res_99_reg_833 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_55;
        res_9_reg_603 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_9;
        res_reg_558 <= call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_ap_return_0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((layer2_out_full_n == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((layer2_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        input_1_TDATA_blk_n = input_1_TVALID_int_regslice;
    end else begin
        input_1_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        input_1_TREADY_int_regslice = 1'b1;
    end else begin
        input_1_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((layer2_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        layer2_out_blk_n = layer2_out_full_n;
    end else begin
        layer2_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((layer2_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        layer2_out_write = 1'b1;
    end else begin
        layer2_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((layer2_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (input_1_TVALID_int_regslice == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_0_val = input_1_TDATA_int_regslice[15:0];

assign call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_10_val = {{input_1_TDATA_int_regslice[175:160]}};

assign call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_11_val = {{input_1_TDATA_int_regslice[191:176]}};

assign call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_12_val = {{input_1_TDATA_int_regslice[207:192]}};

assign call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_13_val = {{input_1_TDATA_int_regslice[223:208]}};

assign call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_14_val = {{input_1_TDATA_int_regslice[239:224]}};

assign call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_15_val = {{input_1_TDATA_int_regslice[255:240]}};

assign call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_1_val = {{input_1_TDATA_int_regslice[31:16]}};

assign call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_2_val = {{input_1_TDATA_int_regslice[47:32]}};

assign call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_3_val = {{input_1_TDATA_int_regslice[63:48]}};

assign call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_4_val = {{input_1_TDATA_int_regslice[79:64]}};

assign call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_5_val = {{input_1_TDATA_int_regslice[95:80]}};

assign call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_6_val = {{input_1_TDATA_int_regslice[111:96]}};

assign call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_7_val = {{input_1_TDATA_int_regslice[127:112]}};

assign call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_8_val = {{input_1_TDATA_int_regslice[143:128]}};

assign call_ret_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_fu_73_data_9_val = {{input_1_TDATA_int_regslice[159:144]}};

assign input_1_TREADY = regslice_both_input_1_U_ack_in;

assign layer2_out_din = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{res_107_reg_873}, {res_106_reg_868}}, {res_105_reg_863}}, {res_104_reg_858}}, {res_103_reg_853}}, {res_102_reg_848}}, {res_101_reg_843}}, {res_100_reg_838}}, {res_99_reg_833}}, {res_98_reg_828}}, {res_97_reg_823}}, {res_96_reg_818}}, {res_95_reg_813}}, {res_94_reg_808}}, {res_93_reg_803}}, {res_92_reg_798}}, {res_91_reg_793}}, {res_90_reg_788}}, {res_89_reg_783}}, {res_88_reg_778}}, {res_87_reg_773}}, {res_86_reg_768}}, {res_85_reg_763}}, {res_84_reg_758}}, {res_83_reg_753}}, {res_82_reg_748}}, {res_81_reg_743}}, {res_80_reg_738}}, {res_79_reg_733}}, {res_78_reg_728}}, {res_77_reg_723}}, {res_76_reg_718}}, {res_75_reg_713}}, {res_74_reg_708}}, {res_73_reg_703}}, {res_72_reg_698}}, {res_71_reg_693}}, {res_70_reg_688}}, {res_69_reg_683}}, {res_68_reg_678}}, {res_67_reg_673}}, {res_66_reg_668}}, {res_65_reg_663}}, {res_64_reg_658}}, {res_63_reg_653}}, {res_62_reg_648}}, {res_61_reg_643}}, {res_60_reg_638}}, {res_59_reg_633}}, {res_58_reg_628}}, {res_57_reg_623}}, 
    {res_56_reg_618}}, {res_55_reg_613}}, {res_54_reg_608}}, {res_9_reg_603}}, {res_8_reg_598}}, {res_7_reg_593}}, {res_6_reg_588}}, {res_5_reg_583}}, {res_4_reg_578}}, {res_3_reg_573}}, {res_2_reg_568}}, {res_1_reg_563}}, {res_reg_558}};

assign start_out = real_start;

endmodule //myproject_dense_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_64u_config2_s
